### ISSUE TITLE
The form is still pristine after removing an array element

### ISSUE THREAD

**Issue by deane** [Textalk/angular-schema-form#102]
When I load a schema with default values, and I remove an element from an array, `ngform.$pristine` is still true.
in `deleteFromArray` you actually trigger validation. Wouldn't it be useful to call `ngform.$setDirty()` too ?

(https://github.com/Textalk/angular-schema-form/blob/master/dist/schema-form.js#L1035 and https://github.com/Textalk/angular-schema-form/blob/master/src/directives/array.js#L96)

**Comment by qstrahl** [comment]
This bug affects me. Let me know if there's any way I can help get this fixed.

**Comment by blazkovicz** [comment]
Isn't it pure angular problem?
