### ISSUE TITLE
Using Json Schema $ref

### ISSUE THREAD

**Issue by Simomultimedia** [Textalk/angular-schema-form#118]
How can I use schema definition and `$ref` within the form?

**I have this definition:**

``` "definitions": {
"CAN_postalCode": {
      "type":"string",
      "title": "Postal Code",
      "pattern":"^[A-Z][0-9][A-Z]( )?[0-9][A-Z][0-9]$"
    }
} ```

**In schema properties:** Referring to the definition about

``` "province":{"$ref":"#/definitions/CAN_province"} ```

Demo link: http://igtestvm1.cloudapp.net:8989/offline/angularschemaform/views/refTest.html

![def](https://cloud.githubusercontent.com/assets/2291356/4612889/bd16ad86-52ce-11e4-9a53-974c385ea11b.JPG)

**Comment by davidlgj** [comment]
Nice! I feel like resolving the refs outside of schema form is more flexible than within. Closing this issue. Complain and I will reopen it.

**Comment by AndreNel7** [comment]
[newer workaround example](https://github.com/Textalk/angular-schema-form/issues/69)

P.S. thanks ippeiukai for showing your workaround... which helped me upgrade it to this one :)

**Comment by marcelchastain** [comment]
@davidlgj any chance we can have this added to the documentation, prominently? 

$refs are a fairly integral part of json schema definitions, and the only mention of the currently-supported-status is buried deep in github issues like this one.

**Comment by Anthropic** [comment]
@marcelchastain it will be a part of the 1.0.0 release and is already in the current alpha. I've just added it to the alpha docs and will push them in the next update.

**Comment by legend80s** [comment]
@Anthropic Can we see the the alpha docs for ref now?

**Comment by Anthropic** [comment]
@legend80s it's in the [docs](https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#ref) for the dev branch. Not much to say though, it just parses using fairly default options. More advanced options may  come in future but not for a while.

**Comment by legend80s** [comment]
@Anthropic  Can I see a demo of how to use $ref. The [docs](https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#ref) is too brief for a newbie
