### ISSUE TITLE
Nullable Types

### ISSUE THREAD

**Issue by neotek** [Textalk/angular-schema-form#146]
Hi
I really like your component. But I have problems with nullable types.
They are just ignored.
My Schema looks as follows, any only Start and Limit are rendered:

![image](https://cloud.githubusercontent.com/assets/6042550/4843007/90c47680-602c-11e4-9818-5b3094f43012.png)

Is there a way to support these?

Thanks

**Comment by Dervisevic** [comment]
We should be able to handle this in some fashion right?

**Comment by fiddur** [comment]
If type is an array of two types in the schema, one of which is "null", the form should be generated based on the other one.  It's a special case, but might be more common than other combination of types.  We used that here before changing praxis to remove the field instead of setting it to null.

**Comment by davidlgj** [comment]
I'm marking this as a bug. I don't think we should support some kind of extra field for the user to actually set null, but we shouldn't fail if "type" property in a schema is a list with null in it, as @fiddur says we should handle it by taking the non null value as the default.

**Comment by luxsypher** [comment]
I am still facing :
Invalid type, expected string)

	$scope.schema = { 
		type: "object",
		properties: {
	        db_contact_details_1: {
	            type: ["null", "string"],
			},
       [...]

	$scope.form = [
	  {
	     key: "db_contact_details_1",
            type: ["null", "string"],
 	    title: $translate.instant('load.static.FORM_DB_CONTACT_DETAILS_1'),
	    placeholder: $translate.instant('load.static.FORM_DB_CONTACT_DETAILS_1') + "...",
	  },
        [...]
