### ISSUE TITLE
Conditionals for arrays inside arrays

### ISSUE THREAD

**Issue by jbaydar** [Textalk/angular-schema-form#148]
It's noted in the documentation under conditionals that this isn't possible, but a solution or workaround would be helpful.

**Comment by davidlgj** [comment]
Hi @jbaydar 

It's noted in the docs since its hard to solve. Currently there is no workaround more than to avoid it.

Could you give me a more info on what kind of form/use case your trying to do? Maybe a new field type could be a solution.

**Comment by mkormendy** [comment]
It seems like everything I need from JSON schema form, like conditionals for arrays inside arrays, is never implemented. And maybe 6 years later I would have hoped that this would have been solved, but nope. 😞

Sometimes having an array inside of an array is the best flow for a user. In mine and others it appears this is the case.
