### ISSUE TITLE
How to make array type schemas work without wrapping them inside an object type

### ISSUE THREAD

**Issue by mohsen1** [Textalk/angular-schema-form#158]
I have this very simple schema: 

```json
{
    "type": "array",
    "title": "People",
    "items": {
        "type": "object",
        "title": "Person",
        "properties": {
            "name": { "type": "string" }
        }
    }
}
```

I want to render a very basic form it but everything I tried didn't work except when I wrapped this into another schema that has `"type": "object"` and used `"key": "my-schema"`.

How can I avoid the wrapping, if possible?

**Comment by davidlgj** [comment]
@mohsen1 I'm sorry, but this will be a "wontfix". :( To do an actual fix inside angular schema form would be to implement the exact same wrapping code you now do outside, and since its a fringe case I'm reluctant add it.
