### ISSUE TITLE
Set `min`, `max` and `step` of a `input[type="number"]` based on the schema

### ISSUE THREAD

**Issue by mohsen1** [Textalk/angular-schema-form#159]
If I have an schema like this: 
```json
{
  "type": "object",
  "properties": {
    "my-number": {
        "type": "integer",
        "minimum": 100,
        "multipleOf": 5,
        "maximum": 1000
    }
}
```

The input filed by should look like this:
```html
<input type="number" min="100" max="1000" step="5">
```

**Comment by Dervisevic** [comment]
To anyone implementing this: The novalidate attribute will take care of this. http://www.w3.org/TR/html5/forms.html#attr-fs-novalidate. It will allow for the browser to add controls and custom keyboards etc but not validate as that is handled by angular schema form via tv4.js.
