### ISSUE TITLE
ngModelController $parsers, $formatters... and $validators  ?

### ISSUE THREAD

**Issue by Sandreu** [Textalk/angular-schema-form#165]
Hello,

I would like to use ngModelController's $parsers, $formatters, and why not $validators properties....
I can do a pull request, but I want to know what you think...

I thought about a sf-form-processor="form" directive.
The directive will look into form.$parsers, form.$formatters and form.$validators to fill the ngModelController.$xxxxx

Perhaps this directive should merge the schemaValidate directive... ?

**Comment by davidlgj** [comment]
Oooooh yeah parsers seems to be a nice thing to expose. Also the very nice `$asyncValidators` could really be useful for "checking if the username is already taken". I'm not making any promises time wise ;)  but its a good idea!

**Comment by Sandreu** [comment]
I migrated to react, I don't like the idea of angular 2... But good luck with your nice project.
Then I will not PR this :)

Regards.
