### ISSUE TITLE
Sufficiently Complicated Forms cause $infdig infinite digest loop error

### ISSUE THREAD

**Issue by quietlyconfident** [Textalk/angular-schema-form#167]
It seems like complicated forms / schemas / models can cause Angular to throw the $infdig error , even though the digest is not actually in an infinite loop, by causing 10+ digest iterations to happen.

If I change the digestTtl to 15 / 20, the error goes away and the application functions normally.

I'm digging into this more (re-writing all my code to make sure it is not my fault), but on initial investigation it seems like forms with conditionals can take several digest iterations to settle out.  If the scope that is including / displaying the schema form is already moderately complicated, ASF can put it over the edge of 10 default digest iterations.

**Comment by davidlgj** [comment]
@quietlyconfident do you still have the issue? Could you give me an example schema and form?

**Comment by loconate** [comment]
Hey. I'm not sure weather to post this here or start a new issue, but I've run into this issue by putting my schema form data into a service and then injecting it into a controller. Then any forms which have a depth of 10 or more will throw the inf. digest loop error i.e.:
```
{"type":"section","items":[
	{"type":"section","items":[
		{"type":"section","items":[
			{"type":"section","items":[
				{"type":"section","items":[
					{"type":"section","items":[
						{"type":"section","items":[
							{"type":"section","items":[
								{"type":"section","items":[
									{"type":"section","items":[
													
									]}
								]}
							]}
						]}
					]}
				]}
			]}
		]}
	]}
]}
```

In my context upping the digest ttl just seems to up the depth at which angular will throw the error.
