### ISSUE TITLE
Put many forms in same $scope and validate for separate.

### ISSUE THREAD

**Issue by mrpotato3** [Textalk/angular-schema-form#169]
Hi. I have a problem with form validation. I need to put more than one different forms and validate/send data separate.

I have:

```javascript
$scope.schema1 = ...
$scope.schema2 = ...
$scope.schema3 = ...
$scope.form1 = ...
$scope.form2 = ...
$scope.form3 = ...
$scope.model1 = ...
$scope.model2 = ...
$scope.model3 = ...
$scope.onSubmitForm1 =function (form)
{
   $scope.$broadcast('schemaFormValidate');  ---> PROBLEM, BROADCAST VALIDATES ALL.
}
$scope.onSubmitForm2 =function (form)
{
   $scope.$broadcast('schemaFormValidate');  ---> PROBLEM, BROADCAST VALIDATES ALL.
}
$scope.onSubmitForm3 =function (form)
{
   $scope.$broadcast('schemaFormValidate');  ---> PROBLEM, BROADCAST VALIDATES ALL.
}
```

I hope somebody can help me.

Thanks!

**Comment by davidlgj** [comment]
I'd say that @mike-marcacci solution sounds good!

**Comment by tmoc** [comment]
I also had this issue and I disagree that multiple controllers is a good solution. Reason being, it drastically increases complexity in some scenarios, such as when you want to share form behavior logic across different parts of the app. It forces you to make multiple controllers all over the place that do nothing but use a single service.

**Comment by Alttaf** [comment]
+1, you should not have to declare multiple controllers to manage just one service gets repetitive and goes agains DRY principles
