### ISSUE TITLE
Adding input type event handlers

### ISSUE THREAD

**Issue by yellowandy** [Textalk/angular-schema-form#172]
Hi, is there anyway to specify or pass in functions we want executed for basic javascritp event handlers?  For instance, I wanted to hook something up for the onFocus event handler on a text input field but was unable to do so.  From reading the code it appears as though only onChange is supported and onClick for button types.  Thanks for the help.

**Comment by davidlgj** [comment]
Hi @yellowandy,

currently no. I guess it could be handled the same way as onChange though. 

What is the use case? What are you trying to do?
