### ISSUE TITLE
sfDecorator asking for new/isolated scope

### ISSUE THREAD

**Issue by morrislaptop** [Textalk/angular-schema-form#175]
```
<form
    class="demeter-schema-form"
  	name="UserImpersonationForm"
  	sf-schema="schema"
  	sf-form="form"
    sf-decorator="everline-schema-form-decorator"
  	sf-model="model"></form>
</div>
```
Then I get the error...

Error: [$compile:multidir] Multiple directives [sfDecorator, sfSchema] asking for new/isolated scope on: <form class="demeter-schema-form ng-pristine ng-valid" name="UserImpersonationForm" sf-schema="schema" sf-form="form" sf-decorator="everline-schema-form-decorator" sf-model="model">

**Comment by davidlgj** [comment]
Ah, that was unfortunate. `sf-decorator` is a bit broken currently. 

A workaround could be to only load your decorator, that way it should default to use it without having to using the `sf-decorator` directive.

**Comment by nikolassv** [comment]
At https://github.com/Textalk/angular-schema-form/blob/development/src/services/decorators.js#L396 the default decorator is named `'sfDecorator'`. Unfortunately, this is also the name of the attribute that determines which decorator to use for a form. Is there any good reason why not to change the name to `'sfDefaultDecorator'` to prevent further scope conflicts?

**Comment by davidlgj** [comment]
Hi @nikolassv,

we'll it'll be a lot easier to just change the name of the attribute to something else since then you don't need to update the templates. So I changed it to `sf-use-decorator` see 446d8465dbe47cc9bce18686064bcc8ec33a1130  

There is still #29 to fix as well though.
