### ISSUE TITLE
Set field dirty and not valid

### ISSUE THREAD

**Issue by jdgblinq** [Textalk/angular-schema-form#177]
I need to be able to set a field as $dirty = true and $setValidity(e,false), as per this guide: http://fdietz.github.io/recipes-with-angular-js/backend-integration-with-ruby-on-rails/validating-forms-server-side.html

How do I do that with angular-schema-form? I see how to set the form as $dirty, but how do I set an individual field?

Thanks

**Comment by rhelgeby** [comment]
Exposing $$key$$ and setting the name attribute like you did would be useful by itself. Then, in the submit callback we will be able to call myForm['fieldName'].$setValidity(...).

**Comment by davidlgj** [comment]
@jdgblinq I agree that model[key + '_error'] looks a bit hackish :-) I'll try to get time to check out the PR today or tomorrow
