### ISSUE TITLE
Custom Styling/CSS

### ISSUE THREAD

**Issue by raghavchandra** [Textalk/angular-schema-form#179]
Hey,
I am not able to figure out how to add classes to forms.

Thanks,
Raghav

**Comment by davidlgj** [comment]
Hi @raghavchandra,

currently there is no way do to this, but it is an often requested feature so it will happen some time in the future.

**Comment by adamschwartz** [comment]
@raghavchandra At Eager we’ve solved this problem by overriding decorator mappings (`schemaFormDecoratorsProvider.addMapping`) and creating custom `format`s. Here are some examples: [https://eager.io/developer/install-json-tester](https://eager.io/developer/install-json-tester).

@davidlgj Happy to help out with this any way I can.

**Comment by davidlgj** [comment]
In the latest release the standard options `htmlClass` and `fieldHtmlClass`  ([docs](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#standard-options)) landed.

Hope that works for you (demo is *not* updated yet though!)
