### ISSUE TITLE
release on npmjs.org

### ISSUE THREAD

**Issue by ebrehault** [Textalk/angular-schema-form#181]
It would be handy to have a release on npmjs.org for people who use NPM (+ Browserify) to manage their dependencies.
Do you think it would be possible?
(I can manage it if you re affraid of increasing your maintenance burden)

**Comment by Dervisevic** [comment]
So, the reason is that we haven't looked at browserify and all that jazz, but if you wanna do it, go right ahead.

**Comment by mike-marcacci** [comment]
Hey there! Sorry to only chime in now, but id like to share my 2 cents: if possible it would probably be better for textalk to manage this on npm as well as bower. It's a pretty trivial extra step (literally just run `npm publish`) whenever you're already releasing to bower, and that's probably the best way to keep the two in sync...

**Comment by davidlgj** [comment]
We be happy to do the publishing! But doesn't it need some kind of wrapping to work with browserify?

**Comment by ebrehault** [comment]
Even if the module is not CommonJS compliant, it is still very useful to publish it on npmjs.org, as browserify is able to deploy non-CommonJS modules (with browserify-shim).
So publishing on npmjs.org can be seen as an easy first step (as @mike-marcacci mentioned), and my original request was limited to that.
But of course, adopting CommonJS compliancy would also be very nice next step.

**Comment by Dervisevic** [comment]
If you guys could check out this pull request and see if everything is dandy with the package.json file that would be great. https://github.com/Textalk/angular-schema-form/pull/202

**Comment by Dervisevic** [comment]
It's now published, let me know if any changes need to be made, and if someone feels they're up to it it's be cool to make it CommonJS compliant. 

https://www.npmjs.com/package/angular-schema-form
