### ISSUE TITLE
Form validity after schema update

### ISSUE THREAD

**Issue by aymericfr** [Textalk/angular-schema-form#182]
Hello,
Here is my issue: depending on some user inputs, the schema is reloaded so the form re-renders. But in this case, the validation always fails as if there were some errors remaining from the previous schema.
Am I missing something here?

**Comment by burdiuz** [comment]
May be we have same issue
https://github.com/Textalk/angular-schema-form/issues/198

**Comment by davidlgj** [comment]
Yes seems to be a duplicate of #198 and #200
