### ISSUE TITLE
Question on using validation library alone

### ISSUE THREAD

**Issue by prashanthseshadri** [Textalk/angular-schema-form#184]
Hi,

I would want to know if there is way to just use the validation portion of the form using Json Schem and not construct the form UI based out of the JSON. If so, can you point me to the right docs? Currently looks to me like validation (of using tv4+JsonSchema+angularJS directive) is clubbed with form generation in the same library (btw i looked at dist/ folder)?

Thanks

**Comment by Dervisevic** [comment]
All of the validation is handled by tv4.js (https://github.com/geraintluff/tv4). You can use that library by itself by supplying a schema for it to validate against. As all ASF does is, generate the form, and hook in the validation, I don't think you need much more from ASF, tv4 should handle what you need.
