### ISSUE TITLE
Working with CSS/Styling

### ISSUE THREAD

**Issue by GerardSoleCa** [Textalk/angular-schema-form#186]
Hi,

I needed to be able to set classes in form elements, so I'm working on a Fork which provides the possibility to add styles to the element (ie. input) or the enveloping div. This can be set by two properties on schema (style and divStyle).

Once it is working fine, I'll like to PR to integrate this feature in this library.

Basically I've added two lines in __/src/services/schema-form.js__:
```js
    //Style attributes
    if (schema.style) { f.style = schema.style; }
    if (schema.divStyle) {f.divStyle = schema.divStyle; }
```

And then, now I'm adding this property to class in the decorators. Ie.:
```html
<div class="form-group has-feedback {{form.divStyle}}" ng-class="{'has-error': hasError(), 'has-success': hasSuccess()}">
  <label ng-show="showTitle()">{{form.title}}</label>
  <textarea class="form-control {{form.style}}"
            sf-changed="form"
            placeholder="{{form.placeholder}}"
            ng-disabled="form.readonly"
            ng-model="$$value$$"
            ng-model-options="form.ngModelOptions"
            schema-validate="form"></textarea>
  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
</div>
```
Thanks!

**Comment by stramel** [comment]
I was wondering how to apply styling to a element. For example I have a link I want to align to the right. I figured it would be something like:

```js
$scope.form = [
  {
    type: 'help',
    helpvalue: '<a href="#">LINK</a>,
    style: 'text-right'
  }
];
```

Is this what this would solve? Is there a better way to do this?

**Comment by GerardSoleCa** [comment]
In my application I'm not using, or at least I'm trying to avoid, the usage of the $scope.form, because is for a backoffice which is scaffolded from the database classes in any kind of application, so I'm attaching the styles to the schema as a property (like is done in the format). Defining two style-properties (divStyle and style) allows to apply css-classes to either the containing div or the element itself.

**Comment by davidlgj** [comment]
@GerardSoleCa  Adding custom classes sounds like a good idea, but I don't like adding things to the schema. The schema follows a standard and adding custom attributes to that standard is not a good thing. I feel styling etc belongs in the form definition. 

The splitting of schema and form definition is one of the key points of schema form and I wouldn't recommend just using a `['*']` definition, but you don't seem to be the only one using it this way :-) so I guess we need to find a solution for you guys as well!

Instead of adding  a ton of extra attributes to the schema, maybe we could add one and let that be the form definition object for that field?

example schema.
```js
{
  "type": "object",
  "properties": {
    "type": "string",
    "enum": ["foo", "bar"],
    "x-schema-form": {
       "type": "select",
       "enumNames": [
          foo: "Foo",
          bar: "Bar"
       }
    }
  }
}
```

I realize I've sidetracked a bit, but what do you think?

**Comment by adamschwartz** [comment]
@davidlgj :+1:

At Eager we’ve mostly been able to solve this problem with `format` ([examples](https://eager.io/developer/install-json-tester)), but I could see `x-schema-form` being a more flexible approach in some ways.

**Comment by GerardSoleCa** [comment]
@davidlgj The ```x-schema-form``` it seems a really good approach to do this, it's more flexible and all can be in a single object.

**Comment by mike-marcacci** [comment]
Hmm, I'm hesitant to break the standard... and keeping the schema and form definitions separate has given me all sorts of flexibility. For example, I can use one schema to define a document stored in the DB, and choose to show different parts of it in my form definitions.

That said, I definitely see this use case. However, perhaps this is something we can make a bit more generic, and propose an addition to the json-schema standard? While the spec itself shouldn't define form-specific fields, it's not unreasonable for it to officially support some attribute for "annotations" or "decorators". This practice is reasonably common in programming languages and is very useful (like [annotating a struct for JSON](https://gobyexample.com/json) in go). This would allow annotated schemas to pass schema validation, and prevent any future name conflict with core features.

I don't believe such a property is designated in the spec right now, but something like `$` might be appropriate anywhere `type` is allowed. Does anyone else have a better feel for how json-schema is being used with other specific-use tools like this one?

**Comment by mike-marcacci** [comment]
@davidlgj I had no idea that was explicitly allowed by the spec! How cool :)

**Comment by davidlgj** [comment]
Hi everyone,

ok. In the latest release the standard options `htmlClass` and `fieldHtmlClass`  ([docs](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#standard-options)) so you can supply your own classes and the above mentioned `x-schema-forms` ([docs](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#form-defaults-in-schema)). 

Hope that works for you (demo is *not* updated yet though!)

**Comment by GerardSoleCa** [comment]
Hi!

I'll try ASAP, thank you so much!
