### ISSUE TITLE
How to handle null values? (invalid type: null (expected string))

### ISSUE THREAD

**Issue by ms88privat** [Textalk/angular-schema-form#193]
Hello,

my specified form schema matches the properties of a model which is coming from a backend server.
A lot of the properties are not necessarily required and have therefore a 'null value'.

For example: 
model = {name: null, id: 32}. 
So my schema looks like this: 
schema = {type: 'object', properties: {name: {type: 'string'}. id: {type: 'integer'}.

The problem is, that i can not validate the form because of null != string. 
 
I really do not want to parse all of the models and properties beforehand....
I think it is related to https://github.com/Textalk/angular-schema-form/issues/146 but there is no solution?

Thank you very much

**Comment by Dervisevic** [comment]
In #146 they do mention the workaround that would allow it, but you would lose the required validation. You mentioned they are not necessarily required so maybe this would work for you.

**Comment by ms88privat** [comment]
setting type: ['null', 'string] does not work. It will not render the input field.

**Comment by Dervisevic** [comment]
Ah, i see. Then its the same issue. I'll tag it as an enhancement.

**Comment by Dervisevic** [comment]
Duplicates #146

**Comment by fiddur** [comment]
As stated in #146 this is fixable with multiple types, but if you have control over the backend, I would suggest skipping the field with null value, so that model is just { "id": 32 } when there is no name.  That gives a cleaner schema, using "required" to say what is required and not having to have multiple types on all non-required fields.

**Comment by ms88privat** [comment]
Thanks for the reply but I do not have control over the backend. The field is not visible if I use the array syntax  title: ['null','string']. Am I doing something wrong or is there a misunderstanding? Thank you.

**Comment by davidlgj** [comment]
I've marked #146 as a bug, it shouldn't break at least. Please move any further comments over on that issue.
