### ISSUE TITLE
validation messages

### ISSUE THREAD

**Issue by stramel** [Textalk/angular-schema-form#194]
How are the tv4 errorCode messaging supposed to work? The documentation doesn't help, would you be willing to add an example that uses the tv4 error codes?

**Comment by Dervisevic** [comment]
Is it this section that you're wondering about? https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#validation-messages

I noticed it wasn't so straight forward when i tried to use it myself, so i'll update it now and it will be shipped with the next release.

**Comment by Dervisevic** [comment]
I've expanded that section, you can check it out here for now. It may also change before it's in master but everything in there should work now. Hope that helps you!

**Comment by stramel** [comment]
:+1: This is exactly what I was looking for! Thanks @Dervisevic

**Comment by stramel** [comment]
@Dervisevic How do you provide `tv4` to an angular application? I thought maybe it would be included in the `schemaForm` module.

**Comment by Dervisevic** [comment]
Yeah it's included in schemaform. I just tried it myself, tv4 is available globally.

**Comment by stramel** [comment]
Sorry, had a derp moment!
