### ISSUE TITLE
Usage without Bootstrap

### ISSUE THREAD

**Issue by machulav** [Textalk/angular-schema-form#195]
Hi,

Can I use this lib without Bootstrap and corresponding classes in generated forms?

**Comment by Dervisevic** [comment]
I don't think it's supported out of the box, and some forks may have done it. If you look in the src folder(https://github.com/Textalk/angular-schema-form/tree/master/src/directives) you will see that there is decorators/bootstrap, that's the templates for the generated elements. You can modify these or create new ones. Unfortunately i don't see that we have documentation on how to create new decorators, but check out out how the bootstrap one is done and that should go a long way.

**Comment by stramel** [comment]
@Dervisevic Isn't this the documentation for creating new decorators? https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md#decorators
