### ISSUE TITLE
Min and Max validation

### ISSUE THREAD

**Issue by ravivit9** [Textalk/angular-schema-form#196]
How to display both min and max Custom validation message.  A sample structure might be helpful.

**Comment by Dervisevic** [comment]
Check out how to specify custom validation messages here: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#validation-messages This is from the development branch and is an expansion to the current part of the manual about custom validation messages. 

Min and max are tv4.errorCodes.NUMBER_MINIMUM (101) and tv4.errorCodes.NUMBER_MAXIMUM (103). 

Does this answer your question?

**Comment by ravivit9** [comment]
In a way yes but, to make it clear
i) Number range using min and max value.
ii) Text length validation based on both minLength and maxLength along with two different custom messages within the form or schema structure as I would wish to retrieve error messages from backend for internationalisation purpose.  

Please clarify what is the number 101 mentioned with in the brackets tv4.errorCodes.NUMBER_MINIMUM(101).

**Comment by stramel** [comment]
@ravivit9 101 in this case is the value associated with the error, an error code if you will. You can see all the errors and their values listed here: https://github.com/geraintluff/tv4/blob/master/source/api.js#L1
