### ISSUE TITLE
Specify Factory Function name to fill Dropdown List

### ISSUE THREAD

**Issue by ravivit9** [Textalk/angular-schema-form#197]
How to specify a rest api function name within the schema or form JSON structure which returns json formatted data from a php script to pulls the recordset from MySql database.  The return data set would be key value pair instead of single enum array of values.  The expected output would be something like the below:
e.g.
[
{100: "USA"},
{101:"UK"}
] 

This way I can define static "form" and "schema" json structure at client side by specifying the factory function name to return the dropdown data from backend to fill the dropdown otherwise I think I may have to generate both the "form" and "schema" json structure which includes dropdown values from backend which is very tedious and also unnecessary call to the backend for every form generation regardless whether it's required to generate the stand fields.

**Comment by davidlgj** [comment]
Hi @ravivit9,

specific use cases like this are easiest to solve by creating your own field type. You can see the docs here: https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md

**Comment by davidlgj** [comment]
Also, I haven't tested it myself but here is one add-on that might fit: https://github.com/networknt/angular-schema-form-strapselect

**Comment by stramel** [comment]
@davidlgj Might be good to add that one to the list on the README?

**Comment by Dervisevic** [comment]
We are working on a new page with a dynamic list of addons and that will be out pretty soon, so that's where people will find these addons.

**Comment by stramel** [comment]
:+1:
