### ISSUE TITLE
Date Picker Implementation.

### ISSUE THREAD

**Issue by ravivit9** [Textalk/angular-schema-form#201]
Currently I am working out how to implement a date picker.  I can see there is an add-on which I have already installed.  Do we have an example implementation of schema and form structure?

I tried to implement the example quoted on the date picker github but gives me an error.  For example.
{
  "schema": {
    "type": "object",
    "title": "Comment",
    "properties": {
      "name": {
        "title": "Name",
        "type": "string"
      },
      "birthday":{
      "birthdate": "birthDate",
      "minDate": "1900-01-01",
      "maxDate": "new Date()",
      "format": "yyyy-mm-dd"
      },
      "email": {
        "title": "Email",
        "type": "string",
        "pattern": "^\\S+@\\S+$",
        "description": "Email will be used for evil."
      },
      "comment": {
        "title": "Comment",
        "type": "string",
        "maxLength": 20,
        "validationMessage": "Don't be greedy!"
      }
    },
    "required": [
      "name",
      "email",
      "comment"
    ]
  },
  "form": [
    "name",
    "email",
    "birthday",
    {
      "key": "comment",
      "type": "textarea",
      "placeholder": "Make a comment"
    },
    {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    }
  ]
}

**Comment by Dervisevic** [comment]
Ok i read the example code on the readme, and it's not super, clear. I'm gonna update it now, but basically the code that is there is for the *form part*, here is an example:

Schema: (Note the type string and format date)
```javascript
{
  "type": "object",
  "required": [
    "birthday"
  ],
  "properties": {
    "birthday": {
      "title": "Bday",
      "type": "string",
      "format": "date"
    }
  }
}
```

Form: 
```javascript
[
  {
    "key": "birthday",
    "minDate": "1900-01-01",
    "maxDate": new Date(),
    "format": "yyyy-mm-dd"
  }
]
```

In the form section, note no quotes around new date, this is when used in a JS environment and not in the tester.

Hope this helps.

**Comment by ravivit9** [comment]
Thanks for the update.  I have now installed the latest version of date picker and included the following file and updated the above script but with double quotes for new Date() as it's giving me an console run time error. if I include within double quotes then just a text box appears.

Included the following 
    <script src="bower_components/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="bower_components/tv4/tv4.js"></script>
    <script src="bower_components/objectpath/lib/ObjectPath.js"></script>
    <script src="bower_components/angular-schema-form/dist/schema-form.min.js"></script>
    <script src="bower_components/angular-schema-form/dist/bootstrap-decorator.min.js"></script>
    <script src="bower_components/angular-schema-form-datepicker/src/angular-pickadate.js"></script>

**Comment by Dervisevic** [comment]
Try removing the max date all together. You can see how it works here http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html in the kitchen sink example.

**Comment by ravivit9** [comment]
The above link example looks great but but when I implement exactly in the same way nothing happens, no error and no date picker comes out just a text box displayed.  All the fields are populating perfectly all right except the date picker.

Am I missing something?

JSON DATA (.schema and .form will be extracted from REST API object)
--------------------------------------------------------------------------------------------
{
  "schema": {
    "type": "object",
    "title": "Comment",
    "properties": {
      "name": {
        "title": "Name",
        "type": "string"
      },
      "email": {
        "title": "Email",
        "type": "string",
        "pattern": "^\\S+@\\S+$",
        "description": "Email will be used for evil."
      },
      "comment": {
        "title": "Comment",
        "type": "string",
        "maxLength": 20,
        "validationMessage": "Don't be greedy!"
      },
      "date1": {
        "title": "Date of party",
        "type": "string",
        "format": "date"
      }
    },
    "required": [
      "name",
      "email",
      "comment"
    ]
  },
  "form":[
    "name",
    "email",
    {
      "key": "comment",
      "type": "textarea",
      "placeholder": "Make a comment"
    },
    {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    },
    {
      "key": "date1",
      "minDate": "2014-06-20"
    }
  ]
}



JAVASCRIPT FILES (Along with angular and jquery).

bower_components/tv4/tv4
bower_components/objectpath/lib/ObjectPath
bower_components/pickadate/lib/picker
bower_components/pickadate/lib/picker.date
bower_components/pickadate/lib/translations/nl_NL

bower_components/angular-schema-form/dist/schema-form.min
bower_components/angular-schema-form/dist/bootstrap-decorator.min
bower_components/angular-schema-form-datepicker/bootstrap-datepicker.min

**Comment by Dervisevic** [comment]
I put your schema and form in the editor i linked above and i get an error on this line:

```"pattern": "^\S+@\S+$",```
When i removed that line it rendered, please try that, and if it's not that i can look further.

Also please mark up your code in the future: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by ravivit9** [comment]
Removed the pattern but still doesn't work.  I wonder am I missing to include any library which may be required?

**Comment by ravivit9** [comment]
I tried my level best to understand the issue but unable to get to the bottom of the issue.  In fact i downloaded the angular-schema-form-master through bower install and tried to access from localhost which hit more errors.  I am not sure whether I am missing anything which may be very basic?

This is a great library / tool which solves many of the manual works and increases the dynamic form building process at a greater extent and efficiently but without myself proving it's working in my local project I am not sure how I am going to implement this.

**Comment by ravivit9** [comment]
Downloaded the angular-schema-form-master and it's working fine locally now I need investigate what I am missing from my main project.

**Comment by ravivit9** [comment]
Finally it worked fine after i included jquery.js first and then angular.js, before it was other way around.

Thanks for all your prompt responses.

**Comment by sixstringer413** [comment]
This works good for something current date as is.. Is there a way to select year for a Date Of Birth field?
Or would I have to use another date picker?

**Comment by rnjailamba** [comment]
Thanks @sixstringer413  youre an angel!
