### ISSUE TITLE
Ability to hide title

### ISSUE THREAD

**Issue by stramel** [Textalk/angular-schema-form#203]
It would be great to be able to hide the `title`. Having no title on schema and form should result in no `fieldset` `title`. 

```js
// Schema
name: {
  type: 'object',
  properties: {
    first: {
      title: 'First Name',
      type: 'string'
    },
    last: {
      title: 'Last Name',
      type: 'string'
    }
  }
}
```

```js
// Form
{
  key: 'name',
  items: [
    {
      title: 'FIRST_NAME',
      key: 'name.first',
      type: 'text',
      placeholder: 'FIRST_NAME',
      validationMessage: {}
    }, {
      title: 'LAST_NAME',
      key: 'name.last',
      type: 'text',
      placeholder: 'LAST_NAME',
      validationMessage: {}
    }
  ]
}
```

**Comment by Anthropic** [comment]
Does, {"notitle": true} in the [Standard Options](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#standard-options) not do this? How should it be different?

**Comment by davidlgj** [comment]
Maybe "supressPropertyTitles" in [Global Options](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#global-options) would work for you?

**Comment by stramel** [comment]
@Anthropic @davidlgj I will check this today, thank you for the suggestions! Also, I think having the styling options available in the Standard Options will help as well.

**Comment by stramel** [comment]
Fieldsets do not seem to be respecting the `notitle` property. 
https://github.com/Textalk/angular-schema-form/blob/master/src/directives/decorators/bootstrap/fieldset.html#L2

**Comment by ricklxm** [comment]
"Fieldsets do not seem to be respecting the notitle property. ". I found this is true? Is there any solution to workaround this?

**Comment by davidlgj** [comment]
@ricklxm  Basically its just a `ng-hide="form.notitle"` that is needed on the legend tag. It just needs to be done :)

**Comment by stramel** [comment]
@ricklxm @davidlgj Please take a look at my PR #414 if you get a chance. I was just too lazy to do it when I originally posted lol

**Comment by davidlgj** [comment]
Thanks @stramel! Your PR is now in the development branch.
