### ISSUE TITLE
Hack/Tip and a proposal

### ISSUE THREAD

**Issue by nicklasb** [Textalk/angular-schema-form#205]
For my purposes, I needed to dynamically provide the content of drop down lists.
Adding drop down content to the form would not be as nice as just having a function call in the form definition. So I created a file, forms.js in literal JS notation instead of JSON:
    
    var a = {
            key: "groups",
            title: "Groups",
            description: "The groups the user belongs to.",
            add: "New",
            remove: "Delete",
            style: {
              add: "btn-success"
            },

            items: [
                {
                    key: "groups[]",
                    type: "select",
                    titleMap: (scope.groups)
                }
            ]
        }
    return a;

and loaded and executed it in the current context with $scope as a parameter;
    
    return $http.get('forms.js').then(function (data) {
            var _form_data = new Function("scope", data.data).call(this, $scope)
    }

and voilà, I could load the list of groups or whatever from $scope.groups or wherever.

However, this is not really dynamic as it happens before I click the drop down box, and until that time, there is a much greater risk that groups may have been added and removed. And worse, it is not valid JSON, hence not serializeable unless sent as a strings, which need generation and so forth.

So I looked at the titleMap and the onChange code and came to the conclusion that it should not be terribly difficult to either add an onPopulate attribute to provide data for selects and similar multiple choice widgets. Or just interpret a plain string value for titleMap as an expression to be run in the angular $scope.

That expression could then be called by the UI, populating the widget when used. Any thoughts?

**Comment by davidlgj** [comment]
Hi @nicklasb,

I'd rather solve it by creating an addon/custom type, it feels a bit cleaner and doesn't complicate the simple field types. Especially doing some kind of async call would complicate todays implementation. Better to encapsulate that in it's own form type. 

It should be pretty straight forward though and it seems like @stevehu is working on something like that here: https://github.com/networknt/angular-schema-form-strapselect

**Comment by nicklasb** [comment]
Ok, I will check that out.
Hm, with regards to the async call, you are right, I didn't think about that at all.
