### ISSUE TITLE
Reset Form + Validation Messages

### ISSUE THREAD

**Issue by dring1** [Textalk/angular-schema-form#212]
If a user submits a form,  before submitted to the server I validate with 
```
$scope.$broadcast('schemaFormValidate');
```
If there were some forms errors and a user user wishes to clear/reset the form, I set the form model to 

```
$scope.form = {}
```

If there were any pervious validation error messages, they will stick around with the now empty model, is it possible to clear the validation messages?

**Comment by dring1** [comment]
Solved
```
*logic*
form = {}
form.$setPristine()
```

**Comment by plong0** [comment]
This worked for me to reset the valid state of form + fields, but the validation messages stayed around.

Adding `$scope.$broadcast('schemaFormRedraw');` after `$scope['myForm'].$setPristine()` does the trick.
