### ISSUE TITLE
call function to get enum values

### ISSUE THREAD

**Issue by chachou29** [Textalk/angular-schema-form#22]
Hello,
I would like to call external functions in schemas to get enum values.
Something like that :
```  
$scope.schema = {
    type: "object",
    properties: {
      name: { type: "string", minLength: 2, title: "Name", description: "Name or alias" },
      title: {
        type: "string",
        enum: "getTitlesValues(...,...)"
      }
    }
  };

getTitlesValues = function(data, ...) {
    if(data.xxx == "YYY")
         return ["a", "b", ...]
}
```
OK, it's easy if you build the schema with javascript
In my case, schemas are stored in DB, and the return values from the external function could change ... if it depend of data entered by the user.
Any idea ?

edit : I said schema ? OK, same question, but the function would be defined in the form.

Thank you !
Philippe

**Comment by samcfc** [comment]
@markbarton thanks for you work, I am also very interested in an example of select populated async :)

**Comment by davidlgj** [comment]
@samcfc @snawbel I found this add-ons searching bower: https://github.com/networknt/angular-schema-form-strapselect

I haven't tried it myself, so I don't now what it does really, but the description looks nice :-) 

I'm closing this issue since the solution is to create a custom add-on.

**Comment by stevehu** [comment]
@davldlgj I did it and I have linked two videos to show how it looks and how to use it. Thanks for the great work!


https://www.youtube.com/watch?v=B-TjSF81uuU


https://www.youtube.com/watch?v=lz8fPcY_VJY

**Comment by markbarton** [comment]
@samcfc <https://github.com/samcfc> @snawbel <https://github.com/snawbel>
Sorry havent had a chance to implement yet.

@stevehu so your method is serverside?

Your intercepting the JSON schema and using Java to populate the values
within the Schema.

On 22 January 2015 at 11:53, stevehu <notifications@github.com> wrote:

> @davldlgj I did it and I have linked two videos to show how it looks and
> how to use it. Thanks for the great work!
>
> https://www.youtube.com/watch?v=B-TjSF81uuU
>
> https://www.youtube.com/watch?v=lz8fPcY_VJY
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/22#issuecomment-71009772>
> .
>



-- 

http://www.markbarton.com

**Comment by Dervisevic** [comment]
Awesome videos @stevehu

**Comment by markbarton** [comment]
@stevehu <https://github.com/stevehu> I should have watched the whole vide0
;-)

On 22 January 2015 at 12:16, Denis Dervisevic <notifications@github.com>
wrote:

> Awesome videos @stevehu <https://github.com/stevehu>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/22#issuecomment-71012150>
> .
>



-- 

http://www.markbarton.com

**Comment by stevehu** [comment]
@markbarton I have two different ways to implement dynamic dropdowns:

Strapeselect is pure dynamic as the dropdown itself has controller and services and they are lazy loaded and registered. It gives you all the flexiblity you need. 

Uiselect example is pre-processed on the server to populate the dropdown values and then the json will be send to angular. Majority of the user cases can be covered this way. 

I serve schema form database and I have extended schema form to have a list of actions that map to rest apis.

Both strapeselect and uiselect were created by

https://github.com/chengz

And I just make it dynamic.

**Comment by stramel** [comment]
I feel like this issue may have gotten off track...

**Comment by nicklasb** [comment]
Hi, just wanted to mention that the fork of schema-form-strapselect I am working on as of 0.7.1, in addition to also being dynamic in a number of ways, now also supports ["filters"](https://github.com/OptimalBPM/angular-schema-form-dynamic-select#filters), the functionality mentioned above where the value of one field affects the contents of another:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select
