### ISSUE TITLE
Disabling submit (or any other button of choice) when form is not valid

### ISSUE THREAD

**Issue by lillereven** [Textalk/angular-schema-form#222]
Hello there,

I am trying to have buttons disable automatically while the form is in invalid state. A trivial thing in unfiltered angular, seemingly non-trivial in schema-form.

Looking over the templates, I cannot see how one would go about disabling a button, be it submit or any other kind, while the form state is invalid (myForm.$invalid === true). 

I am probably thinking too complicated, as usual. Could you please hit me with a cluebat? ;)

Cheers,
Reven

**Comment by davidlgj** [comment]
Hi @lillereven,

yep it's a bit complicated if you use schema form to render the submit, but if you don't its pretty straight forward.

The trick is that schema form directives don't need to be on the form but can be on any element. So this is one way to do it:

```html
<form name="myForm">
  <div sf-schema="schema" sf-form="form" sf-model="data"></div>
  <input type="submit" ng-disabled="myForm.$invalid">
</form>
```

**Comment by stramel** [comment]
:+1: I like this approach better than checking to make sure everything is defined.

**Comment by lillereven** [comment]
While not as controlled as having this managed through an actions block, it would be a workable solution for my case. Thank you. I suggest the maintainer stick this into the documentation or FAQ :)

**Comment by davidlgj** [comment]
It's sort of in the docs under "basic usage", https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#basic-usage, check the example in the end. It doesn't have the `ng-disabled` on the button but it do show that the directives don't need to tagged onto a `form` element.

But of course that can be clarified, and documentation PR's are very very very welcome ;-)

**Comment by jollyrogersfabric** [comment]
I read all the docs but could not find anything about disabling buttons.

Could it be done in the controllers $scope.form?

**Comment by jollyrogersfabric** [comment]
I can see in the console that it is disabled:

ng-disabled=”form.$invalid"

So I suppose I need to build a directive to change the apperance of my bootstrap button...
