### ISSUE TITLE
actions template for submit button uses btn-default instead of btn-primary

### ISSUE THREAD

**Issue by lillereven** [Textalk/angular-schema-form#223]
As the title says, there is a small bug in the actions template for the submit button. Either that, or the documentation for that is wrong.

**Comment by Dervisevic** [comment]
This was a recent change: https://github.com/Textalk/angular-schema-form/commit/d35dca8c6c0edf4977ef8fb865ca88cda01e1a38 but the documentation hasn't been updated. This was due to the guideline that there should only be 1 primary button on a page.

**Comment by Dervisevic** [comment]
I've updated the documentation in the development branch and will go out with the next release.
