### ISSUE TITLE
Inconsistant `fieldset` and `tab` api

### ISSUE THREAD

**Issue by CxRes** [Textalk/angular-schema-form#224]
First of all congratulations on a thoughtfully implemented library.

May be I have not understood this properly but the question I have is that shouldn't `fieldset`, `tab` and `section` have the same api as they essentially create the same ui but displayed differently.

For example, if you were to create a form with `"type":"fieldset"` and `key` bound to an object in the schema with no items supplied, it displays the title and properties of that object in the fieldset. However, one cannot  do this with tabs as one needs to specify `tabs:{items:[]}` otherwise nothing is displayed. I somehow find this counter-intuitive.

Wouldn't it be better if all the three had the same api?

**Comment by davidlgj** [comment]
I'm not sure I follow you, in what way are form type `tabs` same as `fieldset` and `section`? (which are very similar)

As I see it `fieldset`and `section` are groups of fields, but `tabs` are groups of groups of fields :-) 

A `tabs` field *without* any tabs in it, i.e. without any `tabs` declaration in the form definition, doesn't really make any sense. It would just be an empty div. Usually you don't have a `key` option on tabs since they neither bind a value or generate anything from the schema.

**Comment by CxRes** [comment]
You are right in saying that `tabs` are group of groups, but a `tab` is just group. Invoking a `tab` should be sufficient information to to create a `tab-bar`/`tabs` which will have that `tab` (hence atleast one instance of tab) in it.

I presume the concern here is that what happens when given a few sibling objects, the user declares some with `tab` and some with `field` - to which my reply will be render them in order with the first instance of the tab being the spot where the tab-bar is created. So, for example, you have:

`{`
`  "schema":{`
`    "type":"object",`
`    "properties":{`
`      "ObjA":{"title":"Object A","type":"object"},`
`      "ObjB":{"title":"Object B","type":"object"},`
`      "ObjC":{"title":"Object C","type":"object"},`
`      "ObjD":{"title":"Object D","type":"object"},`
`      "PrimE":{"title":"Primitive E","type":"string"}`
`    }`
`  },`
`  "form":[
`    {"key":"ObjA","type": "fieldset"},`
`    {"key":"ObjB","type": "tab"},`
`    {"key":"ObjC","type": "fieldset"},`
`    {"key":"ObjD","type": "tab"},`
`    {"key":"PrimEA","type":"textarea"}`
`  ]`
`}`

here you can create a `fieldset` for `ObjA`, the start a `tabs` which are populated with `ObjB` and `ObjD`, then have a `fieldset` for `ObjC` and finally a `textarea` for `PrimE`.

**Comment by CxRes** [comment]
I would argue that a group of groups is same as a group! A primitive can always be thought of as a group of one.

Simpler way to think about it would be to say that `tabs` is a group of groups then a `tab` is just group. So lets start with thinking about `tab` (singular) first though I promise to return to `tabs` later. Invoking a `tab` should be sufficient information to to create a `tab-bar`/`tabs` which will have that `tab` (hence atleast one instance of `tab`) in it.

I presume the concern here is that what happens when given a few sibling objects, the user declares some with `tab` and some with `field` - to which my reply will be render them in order with the first instance of the tab being the spot where the tab-bar is created. So, for example, you have:

`{`
`  "schema":{`
`    "type":"object",`
`    "properties":{`
`      "ObjA":{"title":"Object A","type":"object"},`
`      "ObjB":{"title":"Object B","type":"object"},`
`      "ObjC":{"title":"Object C","type":"object"},`
`      "ObjD":{"title":"Object D","type":"object"},`
`      "PrimE":{"title":"Primitive E","type":"string"}`
`    }`
`  },`
`  "form":[`
`    {"key":"ObjA","type": "fieldset"},`
`    {"key":"ObjB","type": "tab"},`
`    {"key":"ObjC","type": "fieldset"},`
`    {"key":"ObjD","type": "tab"},`
`    {"key":"PrimEA","type":"textarea"}`
`  ]`
`}`

here you can create a `fieldset` for `ObjA`, the start a `tabs` which are populated with `ObjB` and `ObjD`, then have a `fieldset` for `ObjC` and finally a `textarea` for `PrimE`. 

Thus, I believe `tab` and `fieldset` should have the same api.

Now, let us return bring back `tabs` (plural) and the way we normally tend to think about **tabs** (at least I do and I guess you do as well) . If we were to call an object with `type:tabs`, we want all objects inside it to render under a tab (unless overridden). That is to say we want the particular object to be rendered as `section`/`fieldset` with daughter objects rendered as `tab`.  Perhaps, there is a possibility that in the case where we do not specify the form details for daughter objects, we can specify `type:tabs` to achieve this arrangement - my original suggestion. 

But having thought of about it a little more now, perhaps a better way might be to include a override for daughter defaults (may be upto a certain depth). That is have a property like `daughterObjectType:` which one can specify as `tab`. Of course this would be overriden if explicitly specifying an object with `type:` inside the `form`.
