### ISSUE TITLE
Pull Request or Add On for external select options load?

### ISSUE THREAD

**Issue by Anthropic** [Textalk/angular-schema-form#231]
I wanted to check if you prefer having me create a **pull request** with the following functionality within JSON Schema Form or if I should just leave it at [Angular Schema Form External Options](https://github.com/Anthropic/angular-schema-form-external-options)?

I've created a directive and decorator that looks for the following within the schema
```javascript
links:[
  {
    rel:'options',
    href:'./data/{model.state}/{model.city}/flag.json'
  }
]
```
If found and the type is string and **links[].rel = 'options'** it changes it to use format 'select-external' and then scans the resource URI for any dependencies and then watches them all.

In the above case it adds a watch on model.state and model.city and updates the options from the external resource when any dependant value changes. It uses a regex to change {model.state} to {{model.state}} so that it can use Angular's $interpolate to process the string in the current scope.

I'm not entirely sure I have used the JSON Schema links array as it was meant to be used, but it certainly works for my purpose. The url loads an json schema object with a titleMap defined given that is how Angular Schema Form handles select options, but could in theory be changed to use enum instead fairly easily.

**Comment by davidlgj** [comment]
Cool! An add-on would be nice! We're working on making add-ons more visible by presenting a list based on a bower search. But until that is finished I can add you to the list in the README.md.

**Comment by Anthropic** [comment]
I've put it up, but I've only tested it with my current data, I will try to do a demo using the ASF demo to show how it works a bit better in the next day or two. It is already live at the URL https://github.com/Anthropic/angular-schema-form-external-options now if you want to take a look.

**Comment by Anthropic** [comment]
I updated it to now include support for **enum** values and **filtering**:
To add a filter to pass over the URI just add a filter called **externalOptionUri**
```javascript
.filter('externalOptionUri', function() {
  function externalOptionUriFilter(input){
    var current = input;
    if(typeof current === 'string') {
      current = current.replace(' ','-').toLowerCase();
    }
    return current;
  }

  return externalOptionUriFilter;
})
```
