### ISSUE TITLE
fieldHtmlClass how to use?

### ISSUE THREAD

**Issue by assiomatica** [Textalk/angular-schema-form#232]
Please, show an example how to use fieldHtmlClass !

Thanks

**Comment by stramel** [comment]
You should move this to [StackOverflow.com](http://stackoverflow.com/) and tag it under `angular-schema-form` since it is a question not a feature request or bug report.

**Comment by assiomatica** [comment]
Ok I am trying so:
$scope.schema = {
        type: "object",
        properties: {
            name: {
                type: "string",
                minLength: 2,
                title: "Name",
                description: "Name or alias",
                fieldHtmlClass: "myclass"
            },
            title: {
                type: "string",
                enum: ['dr', 'jr', 'sir', 'mrs', 'mr', 'NaN', 'dj']
            }
        }
    };

but it's not working 
what is wrong?

**Comment by assiomatica** [comment]
Ok I got it!

I am using it in schema in place of form definition.

Now it's works!

Thank you for this very nice directive.

Antonio
