### ISSUE TITLE
Support for conditional expression on individual types

### ISSUE THREAD

**Issue by rhelgeby** [Textalk/angular-schema-form#234]
Since the only special thing about the conditional type is an ng-if directive in the template, it may be useful to support conditional in other types too.

Not very important, though it would simplify some form definitions. The workaround is just to wrap it in a conditional type.

**Comment by Anthropic** [comment]
I was thinking about this myself, it would reduce form definition bloat, I have so many similar conditions the definition is now quite massive.

**Comment by nmorse** [comment]
+1 for options that could reduce *form* complexity. 
I often put a single field in a type:conditional... making an items list of one. 
in #180, I agree w @davidlgj:
 > I think a "condition" on every field could be a solution that would ease up the typing.

Is this something that might be added to sf? Or are there any workarounds that could insert an ng-hide?

**Comment by davidlgj** [comment]
I just pushed form option `condition` onto every field, it's in the development branch. See  the docs there for usage but it exactly is the same as the `conditional` form type (which now is an alias for `section`). 

Love to here your feedback on it!

**Comment by rhelgeby** [comment]
Nice. Your solution is better than mine.

I've just duplicated the ng-if directive in custom templates, because I also needed access to custom variables in the evaluation scope (a part of my dynamic form definition builder).

**Comment by davidlgj** [comment]
@rhelgeby  I' don't know if you've gleaned at the code, but it basically slaps on an ng-if on the decorator directives children, i.e. on the top level of the template. I tried to be smart about it though so of there already is an ng-if it adds it as an `||` statement.

If it fits your needs just close the issue :-)

**Comment by rhelgeby** [comment]
Yes, I've studied that code. When this gets into master I can simplify my custom ng-if directives and avoid duplication so it will combine the built-in expression with my custom expression like you mentioned.

Tank you.

**Comment by davidlgj** [comment]
@rhelgeby no promises, but we're aiming at monday morning for a release.

**Comment by rhelgeby** [comment]
That's ok, no rush. I have already made a workaround.
