### ISSUE TITLE
Support for field dependencies

### ISSUE THREAD

**Issue by Anthropic** [Textalk/angular-schema-form#238]
Is there any support planned for basic field dependencies? I really need this, I can fudge it with conditional, but it just isn't the same and requires doubling up.

In the below example if shipTo is provided and not blank then shipAddress becomes required.

Same if loyaltyIdis provided and not blank then loyaltyBonus becomes required.

I assume this is something better built in than added as an add on?

```javascript
{
	"$schema":"http://json-schema.org/draft-04/schema#",
	"title":"Order",
	"description":"Order billing and shipping information",

	"type":"object",
	"properties": {
		"orders": {
			"type":"array",
			"items": {
				"properties": {
					"order":{"type":"string"},
					"billTo":{"type":"string"},
					"billAddress":{"type":"string"},
					"shipTo":{"type":"string"},
					"shipAddress":{"type":"string"},
					"loyaltyId":{"type":"string"},
					"loyaltyBonus":{"type":"string"}
				},
				"additionalProperties":false,
				"required":["order", "billTo", "billAddress"],
				"dependencies": {
					"shipTo":["shipAddress"],
					"loyaltyId":["loyaltyBonus"]
				}
			}
		}
	}
} 
```

**Comment by Anthropic** [comment]
Oh I noticed this is only proposed in draft 5, damnit

**Comment by sndp-vrma** [comment]
Guys, any solution for this dependency thing?

**Comment by Anthropic** [comment]
There is a change added to allow conditionals on each field type. That kind of covers it, ideally tv4 could add it given tv5-experimental has it, but I don't know their plans.

**Comment by ulion** [comment]
angular-schema-form neither use tv4 to validate the whole model data to the whole schema, nor validate any sub object type model sub node data to the sub-tree of the schema. it only do the validation to the few final level field types according to the schema-validate directive in the type's decorators.

for object type, which reflect to the fieldset decorator, but which do not have ng-model in it, nor I have idea how to validate the sub-schema or the whole schema. even if we do the validation direction with tv4 to the whole schema and model data, how to reflect the error back to the form elements?

the way this project currently used to validate the model data does not benefit from tv4 or json-schema on any advanced validation rules. which should really not happen like this. hope some one can get idea to make it does the work correctly.
