### ISSUE TITLE
Pattern validation for array values not performed?

### ISSUE THREAD

**Issue by nicklasb** [Textalk/angular-schema-form#239]
If I have an array and if I do not select a value or enter an empty values, the array is submitted with an item containing an empty value. Also, an empty value shows a valid check mark.

For some reason, empty value isn't validated against the regular expression and gets submitted. 
I have another JSON-schema validator, server side, that also validates the data, and there the invalid value gets caught. 

Is there some kind of setting involved here? I can't find any related TV4 bugs, and no issues regarding the matter.

**Comment by davidlgj** [comment]
Could you give me an example schema and form def to tinker with?

**Comment by nicklasb** [comment]
Oh, forgot, here is a plunk. Empty array values aren't validated.
http://plnkr.co/edit/DkCHyT?p=preview

**Comment by ulion** [comment]
angular-schema-form neither use tv4 to validate the whole model data to the whole schema, nor validate any sub object type model sub node data to the sub-tree of the schema. it only do the validation to the few final level field types according to the schema-validate directive in the type's decorators.

for array type, which reflect to the array decorator, though which has ng-model in it, but there is no any validation on it, no schema-validate directive either, which was used to validate few final level input field.

the way this project currently used to validate the model data does not benefit from tv4 or json-schema on any advanced validation rules. which should really not happen like this. hope some one can get idea to make it does the work correctly.

**Comment by davidlgj** [comment]
hi @ulion,

that only the visible fields validate against the schema is by design.
There are many occasions when you want only part of a schema as a form. If
you need to validate against the entire schema tv4 got your back.

Regarding no support for more advanced json schema validation like
patternProperties and things like anyOf and oneOf they don't really have a
clear form UI. Its unclear what kind of form they actually should generate.
Its easy to build a form fiels type that while it's correct its not really
a nice ui for anyone to use.

fre 27 feb 2015 14:56 ulion <notifications@github.com> skrev:

**Comment by davidlgj** [comment]
@nicklasb sorry that is has taken so much time to get back to you. 

But aren't you missing a required for the array? I think the pattern property check does not apply if the value is empty. For that you need required.

**Comment by nicklasb** [comment]
No problem. It turned out waint that was quite correct, boy do I feel dumb. 
For some reason I wen't all XML schema about it an confused it with minOccurs. 
You are right of course, adding it to the required properties produces the correct behaviour.

Sorry about wasting your time, closing the issue!

**Comment by davidlgj** [comment]
no problem at all :)

fre 27 feb 2015 18:55 Nicklas Börjesson <notifications@github.com> skrev:

**Comment by ulion** [comment]
well, when I talk about "advanced validation rules", indeed I mean the
basic validation rules, e.g. "required" object, should be done at least by
fieldset type, but which do not include any validation code. if it did,
then it can auto benefit from tv4 to get all "dependencies",
"minProperties", etc validations rules works. the fieldset is visible, I
don't think we are validating any invisible datas here. the same for the
whole model and schema.

even we manually do the validation to the whole schema and model data,
normal user have no idea how to make it reflect to the certain
field/fieldset to show the error message, but you guys do, this should be a
native work of the project.

there must be some way to do these properly, any idea?


2015-02-28 1:19 GMT+08:00 David Jensen <notifications@github.com>:

> hi @ulion,
>
> that only the visible fields validate against the schema is by design.
> There are many occasions when you want only part of a schema as a form. If
> you need to validate against the entire schema tv4 got your back.
>
> Regarding no support for more advanced json schema validation like
> patternProperties and things like anyOf and oneOf they don't really have a
> clear form UI. Its unclear what kind of form they actually should generate.
> Its easy to build a form fiels type that while it's correct its not really
> a nice ui for anyone to use.
>
> fre 27 feb 2015 14:56 ulion <notifications@github.com> skrev:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/239#issuecomment-76432564>
> .
>



-- 
Ulion

**Comment by nicklasb** [comment]
I am not sure that this issue is the proper forum for that question, as it has been answered and is closed.
Instead I would recommend you to open a new issue.

**Comment by ulion** [comment]
I do have new issue certainly #270
but as you see, no one is there.

**Comment by nicklasb** [comment]
Well, I hardly think you will speed up the handling of your issue by posting here, they will get to it eventually.
Meanwhile, I would advice you to make your case clearer and also make a working plunkr example so it is easy for them to see the error in action.

**Comment by ulion** [comment]
Thanks for your advice. in #270, the problem is quite clear, please check, just copy and paste the schema and form into http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html

then click button, you will see it does not catch the expirationDate object undefined invalid, and the object expirationDate is "required" in schema clearly.

**Comment by valix85** [comment]
I have same problem, teste on your page 
Form:

[
  "*",
  {
    "type": "submit",
    "title": "OK"
  }
]


Schema:

{
  "type": "object",
  "title": "Types",
  "properties": {
    "string": {
      "type": "string",
      "required":true,
      "pattern":"[0-7]{3}"
    },
    "integer": {
      "type": "integer"
    },
    "number": {
      "type": "number"
    },
    "boolean": {
      "type": "boolean"
    }
  },
  "required": [
    "number"
  ]
}


if I set as w3c pattern="[0-9]{3}" in your schemaform is valid for more character...I think this is an error.. with regex works better, but field name is pattern! how can i set html5 pattern?

**Comment by ulion** [comment]
try to add '^' and '$' into your pattern, then see whether it works.

2016-06-24 15:56 GMT+08:00 Valerio <notifications@github.com>:

> I have same problem, teste on your page
> Form:
>
> [
> "*",
> {
> "type": "submit",
> "title": "OK"
> }
> ]
>
> Schema:
>
> {
> "type": "object",
> "title": "Types",
> "properties": {
> "string": {
> "type": "string",
> "required":true,
> "pattern":"[0-7]{3}"
> },
> "integer": {
> "type": "integer"
> },
> "number": {
> "type": "number"
> },
> "boolean": {
> "type": "boolean"
> }
> },
> "required": [
> "number"
> ]
> }
>
> if I set as w3c pattern="[0-9]{3}" in your schemaform is valid for more
> character...I think this is an error.. with regex works better, but field
> name is pattern! how can i set html5 pattern?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/json-schema-form/angular-schema-form/issues/239#issuecomment-228280962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKsHZsfgE3_FkFlBdEVRxdpKqlstZIuks5qO42WgaJpZM4DZhvP>
> .
>



-- 
Ulion

**Comment by valix85** [comment]
@ulion i don't wan't use a regex non standard html5 w3c ...i think it's better call it filter and implement regular html5 code, i fix with regex but isn't good practice for me

**Comment by ulion** [comment]
pattern is json-schema standard, it is regex.

it's not related to h5 anyway.

2016-06-25 7:59 GMT+08:00 Valerio <notifications@github.com>:

> @ulion <https://github.com/ulion> i don't wan't use a regex non standard
> html5 w3c ...i think it's better call it filter and implement regular html5
> code, i fix with regex but isn't good practice for me
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/json-schema-form/angular-schema-form/issues/239#issuecomment-228492435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKsHUWm2-iAyCJTvcZr8_8FvsMnXMI2ks5qPG9kgaJpZM4DZhvP>
> .
>



-- 
Ulion
