### ISSUE TITLE
Invalid assumption in scope.validateArray

### ISSUE THREAD

**Issue by nicklasb** [Textalk/angular-schema-form#240]
In scope.validateArray (https://github.com/Textalk/angular-schema-form/blob/master/dist/schema-form.js#L1156):

              // Since we prefill with empty arrays we can get the funny situation
              // where the array is required but empty in the gui but still validates.
              // Thats why we check the length.
              var result = sfValidator.validate(
                form,
                scope.modelArray.length > 0 ? scope.modelArray : undefined
              );

The problem is that if one starts with an empty `{}` model and `startEmpty: true`, this is not correct. 
In those cases there is no array at all. Hence I get 
`TypeError: Cannot read property 'length' of undefined
    at link.scope.$watch.scope.validateArray (https://127.0.0.1:8080/admin/bower_components/angular-schema-form/dist/schema-form.js:1149:33)`
on validation of the form, despite the data being correct.

To not have an array at all is correct, if an array isn't required, there is no point in there having  a `"arrayname": []`, and to the best of my knowledge, that is how JSON schema defines it.

**Comment by nicklasb** [comment]
Ok, now this just happens "sometimes", this might be a local phenomenon. I'll be back.

**Comment by Dervisevic** [comment]
How did it pan out @nicklasb ?

**Comment by nicklasb** [comment]
Sorry, I haven't encountered this now for a while. I might have been some underlying stuff, closing.
