### ISSUE TITLE
Allow bypassing of validation so add on developers can do it themselves

### ISSUE THREAD

**Issue by Anthropic** [Textalk/angular-schema-form#241]
Creating an add on that needs to handle the validation for an entire object I need to be able to ignore the default validation and do it myself. I was able to do it with the following as long as
I altered jsonSchema validator with **form.allowInvalid === true**
```javascript
validator.validate = function(form, value) {
    if (!form || form.allowInvalid === true) {
        return {valid: true};
    }
```

What I am doing in my directive
```javascript
if(schema.properties && schema.anyOf) {
    scope.schemaValidate.schema.allowInvalid = true;
    delete schema.properties;
};
ngModel.$validators = {
    anyOf: function(modelValue, viewValue) {
        tv4.validate(scope.ngModel, schema);
        return tv4.valid;
    }
};
```

Open to better ideas?

**Comment by davidlgj** [comment]
So the add-on wants to validate the object but use schema form to render all the fields inside it?

**Comment by Anthropic** [comment]
Essentially I'm executing tv4 validation on the whole object with multiple sub keys, partially so I can use anyOf, but also because I'm displaying related fields that need to be calculated together their display is inline and I don't want the validation to appear on each field but as a whole.

**Comment by ulion** [comment]
@Anthropic how you did the validation with tv4? when the validation not passed, how it reflect the error message back to related form element?
I'd like to benefit from the json-schema validation but current angular-schema-form implement does not validate the whole schema nor the sub object type schema, so many json-schema validation rules indeed is not supported, it's really a shame. hope someone can make it correct.

**Comment by Anthropic** [comment]
Tv4 is always available, just pass the data and schema in for the level
being viewed. You can find an example in the source of angular-schema-form
validation function. I plan to release another add-on for this when I get
over my current cold.

**Comment by ulion** [comment]
can you show me how you did this with the expirationDate sample to validate on the expirationDate schema level?

**Comment by Dervisevic** [comment]
Have you tried the 'schemaFormValidate' event?

**Comment by ulion** [comment]
only 2 places in code listen on schemaFormValidate  event, one is array
directive, because some special case, I think it's a workaround for
some basic case the validation not works, so the array code have to do the
validation by itself. the other place is schemaValidate directive, but it's
obviously only few type of inputs are using the directive, so many of type
fields not do any validation, include fieldset (which be used for "object"
type by default, then any object's inner advanced validation rule won't be
tested at all). and also no any code to validate the whole schema to the
whole model data, it's totally strange to not do that.



2015-02-27 23:19 GMT+08:00 Denis Dervisevic <notifications@github.com>:

> Have you tried the 'schemaFormValidate' event?
>
> On Fri, Feb 27, 2015 at 3:36 PM, ulion <notifications@github.com> wrote:
>
> > can you show me how you did this with the expirationDate sample to
> validate on the expirationDate schema level?
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/Textalk/angular-schema-form/issues/241#issuecomment-76403420
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/241#issuecomment-76410339>
> .
>



-- 
Ulion

**Comment by Anthropic** [comment]
I believe __disableErrorState__ covers what I was after, I will reopen if I find it needs further changes to accomplish what I was after.
