### ISSUE TITLE
AngularStrap Plugins

### ISSUE THREAD

**Issue by MarZab** [Textalk/angular-schema-form#242]
I want to start a plugin for ngStrap, I want know know if there are any other people who want to do the same.

I implemented the first widget, Select, here
https://gist.github.com/MarZab/6b8cda742768b9915146

**Comment by terranisu** [comment]
Well, we are using angular-strap with angular-schema-form in our project, but I'm not quite sure that the plugin for ngStrap is a good idea. The angular-schema-form gives your a great opportunity to create your own types and you can create your own html-template with any ng-strap element in it. So I don't know how ngStrap plugin will help to improve this process?

**Comment by MarZab** [comment]
So I found this on the new webpage, seems like something is already brewing.

https://github.com/networknt/angular-schema-form-strapselect

**Comment by nicklasb** [comment]
Hi, It certainly is, and I have been involved in that brewing lately, but regrettably neither stevehu(networknt) or chengz(that started with the plugin) have any time working on it. 

However, I do, and they both basically said I ought to continue on my own fork so I did:  
https://github.com/OptimalBPM/schema-form-strapselect

It is now more harmonized with angular-schema-form,  settings have moved into the form and also values can be fetched from backends and callbacks in a number of ways.

Please take a look. I am a sucker for pull requests. :-) 

And also, I don't think it is a good idea to point at the stevehu repository on the angular schema webpage, that should be updated to point at this one, stevehu's repository is already long way behind the above mentioned and as I have understood it he will remove it to not confuse things.

**Comment by nicklasb** [comment]
Ok, so now I have updated the (bower) repository name to the more correct: https://github.com/optimalbpm/angular-schema-form-strapselect

**Comment by Dervisevic** [comment]
Please note, for it to show up in the listing, the name should either be named angular-schema-form-* or be keyworded/tagged with angular-schema-form-add-on. I saw that yours had neither, just a heads up if you want it to be up there.

**Comment by nicklasb** [comment]
I have just changed the name, is it correct as it is now?

**Comment by Dervisevic** [comment]
Nah, as the name has no angular in front of it it won't be picked up.

On the keyword front you have "angular-schema-form" but you need to add `angular-schema-form-add-on` like below and push a new version to bower.

```javascript
  "moduleType": [
    "globals"
  ],
  "keywords": [
    "angular-schema-form-add-on",
    "angular-schema-form",
    "schema-form",
    "form",
    "json",
    "json-schema",
    "schema"
  ],
  "license": "MIT",
```

Sorry for the hassle, we just want to make sure it's explicit so the people that want to be on the list are there, and not other packages.

**Comment by nicklasb** [comment]
Aha, thanks! Now I get it.
There were actually quite a lot of things to address in the package and its configuration files, i realized, but now it should all work..i hope?

**Comment by Dervisevic** [comment]
Yup, looks like it. When it pops up on bower, it'll be out on the site (with a little delay as the result is cached)

**Comment by nicklasb** [comment]
Ok.

**Comment by Dervisevic** [comment]
One thing, won't it collide with http://bower.io/search/?q=angular-schema-form-strapselect (networknt's package) now?

**Comment by nicklasb** [comment]
Hm. It will, I suppose. But there is the difference in the repository location. Not sure how that site handles that. He will as far as I know delete that repository, maybe that resolves that problem?

No, i have changed the name. I am not a fan of diverging from convention.

**Comment by Dervisevic** [comment]
If he deletes it it won't be a problem. I tried looking up how bower handles duplicates, but can't find anything.

**Comment by nicklasb** [comment]
It seems that stevehu has to unregister from bower before I can register, I have asked him to do that, so hopefully all will be up soon. It is a less than optimal situation with that old repo being pointed to.
