### ISSUE TITLE
Validation Message

### ISSUE THREAD

**Issue by rexebin** [Textalk/angular-schema-form#245]
Hi, the validation messages from tv4 are somewhat machine language, i.e the use of {key} rather than title or displayName in the messages, which is not the best for production. 

I suggest to introduce the Inflector in ui.utils to humanize the message in the template in bootstrap-decorator.js by default, of course this would require ui.utils as a dependency. 

Or separate the template to config, so we could overwrite the above template if dependency is a big problem.

I tried to follow the documentation to overwrite the validateMessage via globe option, however, it is either all all non, i.e. if I put overwrite one message in the option, all other default messages are gone. Which make this option useless. Moreover, overwriting the message via globe option can only use static messages correct me if I am wrong. 

I use breeze together with angular-schema-form. I am aiming to write one single function to generate schema for all my entities, hoping most of the time not needing to individually config the forms. Therefore, validation rule would come from breeze to schema. Using form for validation is not suitable for this situation.

**Comment by davidlgj** [comment]
Yes the validation messages are a bit troubling, one of the problems is that it is tv4 that interpolates, so for a real solution it probably should go into tv4js. 

But of course we probably could switch on the error code coming out of tv4 for a field and interpolate strings or similar. You are right setting validation messages via the `validationMessage` form option is static.

That all default messages disappear for you is strange, can you give me an example schema and form?

**Comment by plong0** [comment]
FWIW I have a fork over at https://github.com/TechNaturally/angular-schema-form where I tweaked the `scope.errorMessage = function(schemaError){ ... }` code to allow token replacements in the error messages.  I've only implemented key, title, minLength, maxLength tokens so far, but it's super easy to add more.

I like this approach because it allows to specify friendly and specific error messages in formDefaults.

**Comment by davidlgj** [comment]
There are changes in the development branch that adresses this as well, validationMessages now support angular interpolation, see docs here:  https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#validation-messages
