### ISSUE TITLE
Bootstrap select plugin: angular-schema-form-strapselect

### ISSUE THREAD

**Issue by nicklasb** [Textalk/angular-schema-form#246]
Hi all,

Not sure where to post this, but the last year a new plugin, a bootstrap select dropdown plugin has been developed, first (and mostly) by [chengz](https://github.com/chengz), then [stevehu](https://github.com/stevehu), and finally myself. As neither of them have much time to spend on the project and I do, I have now taken it upon myself to care for and lovingly maintain it. :-)

I would like take the opportunity to invite you all to test it and report any issues you might encounter, and of course pull requests are always most appreciated. I have some time in the the nearest weeks to work on this if needed. 

### Features:

* Single and multiple select
* Static and dynamic lists
* Sync and Async callbacks
* HTTP JSON GET/POST convenience functions

### Repository
More information, installation and documentation at:
https://github.com/optimalbpm/angular-schema-form-strapselect

### Future plans:
* More testing
* Also including the ui-select component

### To early adopters:  
It you are already using the older (angular-)schema-form-strapselect iterations, migrating to the newer versions it pretty easy, it is basically a copy-paste operation. The major difference is that the settings have move from the schema to the form. 
This for the reason that the same JSON schema might be used in a number of situations, storing UI widget specific information there is not appropriate, or in many cases even possible. Changes:
 
1. The "format" setting in the schema form is no longer used to set the select type as the JSON schema format setting deals with data types, not UI settings. Some JSON validators might stop on this. That setting is now the form type.
2. The static items array has moved into the form definition(where it is anyway in angular schema form).
3. The array has now value/name names instead of value/label, again to harmonize with the existing selects.
4. The main file is now called angular-schema-form-strapselect.js or angular-schema-form-strapselect.js, nothing else.

**Comment by Dervisevic** [comment]
Tweeted it out :) https://twitter.com/ngschemaform/status/565437733020397568

**Comment by nicklasb** [comment]
Great, thanks!
