### ISSUE TITLE
copyValueTo fails with numeric type

### ISSUE THREAD

**Issue by Anthropic** [Textalk/angular-schema-form#247]
I need to enter a number and have another field populate with that value as default with the user able to override it, exactly what copyValueTo does for strings, but I need it to work for numeric types.

I would see this as most likely an change required in sfSelect which is not trying to parse into the appropriate format for the field type.

The annoying part is I can't start adding it to my forms in advance as at the moment it errors as below when it sets a numeric field to a string and then fails validation!
 
![image](https://cloud.githubusercontent.com/assets/1182507/6144482/5540dfb6-b22c-11e4-9153-2bceb6795d13.png)

**Comment by Dervisevic** [comment]
Bah, ah well. I'll look into this as soon as i have some time over. If you need it urgently, take a look at https://github.com/Textalk/angular-schema-form/blob/master/src/directives/schema-validate.js#L24 that's where the code it, see if you can see why it would fail.

**Comment by Anthropic** [comment]
Thank you so much @Dervisevic, desperate for this functionality, if I knew how to dev on this more than just doing add-ons I'd try to do it myself, but I haven't got time before my holiday next week to get up to speed :(

**Comment by Anthropic** [comment]
@Dervisevic I fixed it in my fork https://github.com/Anthropic/angular-schema-form/ I have to leave the office now so I will request the pull later when I am at home.

**Comment by Dervisevic** [comment]
Awesome!

**Comment by Anthropic** [comment]
Hi @Dervisevic I created #253 pull request, I targeted develop branch as the contribution MD specifies.

**Comment by Dervisevic** [comment]
Perfect @Anthropic, i'll merge it in the morning (or now if you make the changes below) when i get to work, and i'll see when we can get a release out. Thanks so much for reading Contributing.md and targeting development :) 

One thing that would really help with the merging is if you could remove the changes to the generated files in dist/ as they can conflict with other contributions and they're generated when a new release is made. This is also in the file but i need to make it more prominent. 

Thanks so much for finding a fix!

**Comment by Anthropic** [comment]
Damn it, I read that line and forgot, sorry my mother's in hospital so I'm a bit of a mess at the moment.

@Dervisevic I'm a bit new to this, can I change the current pull or do I have to create a new one?

**Comment by Dervisevic** [comment]
Oh, I'm so sorry to hear about your mother, hope she recovers, once again thank you for the PR merging it now.
