### ISSUE TITLE
Overloading Templates

### ISSUE THREAD

**Issue by stramel** [Textalk/angular-schema-form#248]
Am I missing an obvious way to override specific templates without having to recreate all the templates or a custom decorator type?

**Comment by Dervisevic** [comment]
I'm not sure if this is exactly what you're looking for, but you could always overwrite a decorator template, or just edit https://github.com/Textalk/angular-schema-form/blob/master/src/directives/decorators/bootstrap/bootstrap-decorator.js and change what template should correspond to which type?

**Comment by stramel** [comment]
I am wanting to override the checkbox template for the custom styling that I have applied. 

So are you saying load the custom template into `$templateCache` to override the default one?

**Comment by Dervisevic** [comment]
Oh yeah, forgot about templateCache. You basically have 2 option, you can just edit the standard checkbox template, that has to be the easiest way. You can also just make a new one, put it in template cache and specify it's path in the decorator file i linked above. Shouldn't be a problem.
