### ISSUE TITLE
Checkboxes for an array don't seem to have two-way binding

### ISSUE THREAD

**Issue by armyofgnomes** [Textalk/angular-schema-form#25]
If you update the variable on the model that the checkboxes are bound to, they don't check/uncheck. Is this the way it's supposed to work?

I'm trying to load an existing object so that you can edit the current properties. The selects/inputs all work fine, but checkboxes aren't coming through as checked.

**Comment by kevinc** [comment]
@davidlgj not sure if this is completely fixed. We're loading a new instance of the object which doesn't have the same values in the array, but the checkboxes are remaining checked.

For example,
```
$scope.model = { arr: ['a', 'c', 'd'] }; // Checkboxes  for a, c, and d are checked

// Through some api call model changes
$scope.model = { arr: [] }; // Checkboxes seem to still be checked for a, c, and d
```

From what i can see the `$scope.modelArray` that is being watched in the commit that's here isn't be updated to reflect the new values.

**Comment by davidlgj** [comment]
Aww chucks, I'll reopen the issue.

**Comment by ahsalini** [comment]
When we can expect this to be fixed or at least is there any workaround?
Thanks.

**Comment by davidlgj** [comment]
I can't give any ETA:s, but the workaround would be to redraw the form by issuing a `schemaFormRedraw` event https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#updating-form

**Comment by Dervisevic** [comment]
Well, it's out
