### ISSUE TITLE
Object Required Validation

### ISSUE THREAD

**Issue by stramel** [Textalk/angular-schema-form#251]
It doesn't seem as thought the required array does not respect object property keys. The select boxes do not get the `has-error` class upon validation when nothing is selected. When selecting something the validation `has-success` works properly. If left blank and is required though does not validate properly.

Example (Simplified Code): 
```js
scope.schema = {
  type: 'object',
  required: [
    'expirationDate', // Doesn't work
    'expirationDate.month', // Doesn't work
    'expirationDate.year' // Doesn't work
  ],
  properties: {
    expirationDate: {
      type: 'object',
      properties: {
        month: {
          type: 'string',
          enum: monthsOfYear
        },
        year: {
          type: 'string',
          enum: getValidCcYears()
        }
      }
    }
  }
};

scope.form = [
  {
    key: 'expirationDate',
    items: [
      {
         key: 'expirationDate.month',
         type: 'select'
      },
      {
         key: 'expirationDate.year',
         type: 'select'
      }
    ]
  }
];
```

**Comment by Anthropic** [comment]
Require is designed to be for the current object's properties not sub properties ([Require Definition](http://json-schema.org/latest/json-schema-validation.html#anchor61)), try this and if it works please close the issue :)
```javascript
scope.schema = {
  "type": "object",
  "properties": {
    "expirationDate": {
      "type": "object",
      "properties": {
        "month": {
          "type": "string",
          "enum": ["Jan","Feb"]
        },
        "year": {
          "type": "string",
          "enum": ["2014","2015"]
        }
      },
      "required": [
        "month",
        "year"
      ]
    }
  }
};
```
If you want specific properties on an a sub object, that can be handled using OneOf, ManyOf etc... which are not yet supported. They are already desired for future, just not scheduled yet from what I understand. I made a work around for myself as described in #241 and I am awaiting a further response to that before trying to implement an add on.

Hope that helps :)

**Comment by stramel** [comment]
@Anthropic I have tried that before and forgot to add that in the list of tried `required` properties. I did not work.

**Comment by tmcgee123** [comment]
The suggestion that Anthropic has actually does work, please not that the "required" object must be inside the "expirationDate" object. Our first try we wrongfully put the month and year with the parent "required" and did not create the child like the example shows.

**Comment by stramel** [comment]
Whoops, good point!
