### ISSUE TITLE
Dynamic form changes

### ISSUE THREAD

**Issue by airdrik** [Textalk/angular-schema-form#255]
I've got a situation where one of the form elements' options are dependent on the contents of another element.  The dependent element is a checkboxes element and the source is an array field in the model (represented as a tabarray form element).  As items are added, removed, renamed or rearranged in source array in the model then checkboxes need to be added, removed, renamed or rearranged accordingly to match.  
The problem I have is that if I try to update the form definition for the checkboxes after the layout has already been created, the changes don't show up on the page - no checkboxes appear.  If I wait to create the form+element which has the checkboxes until after I've loaded the model (so I can fill out the titleMap for the checkboxes element from the values in the model) I get errors from angular about $infdig infinite digest loop error (though I believe the checkboxes do show up, but I can't get them to stay in sync with changes).  

I've also run into other cases where I've tried updating the form after the layout was created and it didn't update the layout.

Is there a way to tell schema form to update the layout for a given form element (or the whole form) when changes are made?

**Comment by plong0** [comment]
+1 wondering the same thing...

**Comment by plong0** [comment]
dug into this a little more after a good night sleep to realize it was the error:
TypeError: Cannot read property 'updateOn' of undefined

and a fix at line 175 of schema-form.js (in the createDirective function )
if (form) {
  form.ngModelOptions = form.ngModelOptions || {};
  scope.form  = form;
....

form is updating asynchronously

**Comment by davidlgj** [comment]
@plong0 Interesting! That `upatedOn` error has been coming and going, I knew it had something to do with `ngModelOptions` but I couldn't reliably reproduce. See #206 

The change seems safe though so I'm going to throw it in just to see if it works :-) Thanks for that!

**Comment by davidlgj** [comment]
@airdrik for performance reason we don't want to do a deep watch of the entire form and schema, so currently to redraw the form the  form definition *instance* needs to change, i.e. the form needs a new array. One way to do it is to use `angular.copy()`.

But in the next release you can broadcast the event `schemaFormRedraw` after you've done a change and the form will be redrawn. It's in the development branch now, see docs here https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#updating-form

**Comment by airdrik** [comment]
Thanks.  I understand the performance implications.  The form that I have takes some time to draw, so I'm going to see if I can speed things up by splitting it up into collapsible sections and only create the parts that are uncollapsed, or maybe even replace some of the tabarrays with modal dialogs.

In any case, the schemaFormRedraw event should be sufficient for our needs.

**Comment by davidlgj** [comment]
@airdrik great,

It takes time to draw? Thats interesting, how large is it? I wonder where it spends most of its time. We haven't had any performance issues yet so I have not spent any time optimizing stuff.

**Comment by airdrik** [comment]
I haven't taken much time to look into what the exact cause of the slowness is (it's been taking a few seconds for it to load the page with the forms).  I have some suspicions though.
The form that I'm building has a couple fairly large tabarray elements: the rows and columns elements.  The column subform has 6 other elements plus 4 conditional elements with 1-3 additional elements.  The row subform has 3 other elements plus a checkboxes with a checkbox for each column.  On average there are probably around 12 rows or columns, though some configs have as many as 50 columns and others have well over 100 rows.  The configs I've been testing this out with so far have about a dozen columns and a handful of rows and they take a couple seconds to come up. 

Testing out one that has about 700 rows (resulting in 700 tabs in a tabarray) and 9 columns, it takes about a minute to load/draw the whole form.  Another with 280 rows and 6 columns takes about 20 seconds, and another with 54 columns and 4 rows takes about 6-8 seconds.  It seems there is some correlation between the number of tabs in a tabarray and the time to draw everything.

**Comment by davidlgj** [comment]
Interesting indeed!

**Comment by orderofout** [comment]
I'm having similar performance issues as @airdrik where the schema form fields take some time to display. I've split 233 fields into 8 pages of form fields and there is still a bit of a delay when loading.

**Comment by davidlgj** [comment]
@orderofout, @airdrik I've done some experimenting to see what takes so much time. I did a form with `{ type: 'tabs' }` with 100 tabs, and in each tab 10 text fields, so all in all 1000 inputs. This takes about 12s to DOMContentLoaded event. 

So I thought the double ng-repeat (one around the tabs and then one around each field) would be the culprit and I wrote my own function to just generate the DOM elements needed. It turned out that it didn't get any faster! 

What did change the speed was ripping out the `$compile` i do in the `link` function for each field. This made a huge difference, getting it down to about 5s, so basically cut the time in half. Sadly I do the `$compile` for several reasons, one being able to have one directive, `<sf-decorator form="form">` that uses different templates depending on form type, and the other being that I fix the mapping of ngModel for each field. 

The last part I can get around with extra watches, but the first one is really difficult, even splitting it into several directives, each with a different template , only solves half of the problem, for *how* do I do an repeat over items for each tab page? I think it can be done, but doing it I will need to do a considerable rewrite of schema form, which probably break add-ons etc. Not to mention take a lot of time.

**Comment by thallukrish** [comment]
@davidlgj  I have a need to dynamically modify a dropdown list based on selection of another dropdown list. When I change the schema of the dropdown list by updating the enum, doing angular.copy of the schema into a new obj and the form into a new array, and doing a broadcast of 'schemaFormRedraw', I do not see the list dropdown getting refreshed with the new enum that is updated. 
I am using 0.8.2 of schema-form. 

Can you please tell me where I am going wrong?
