### ISSUE TITLE
complex key for field type select causes error

### ISSUE THREAD

**Issue by anurit** [Textalk/angular-schema-form#256]
It isn't possible to add key (name) for filed of type select witch is array:
"keyname[\"1\"]": {
        "title": "Select with titleMap",
        "type": "string",
        "enum": ["a","b","c"]
 } 
This is possible for type checkboxes, but why not for select?

**Comment by davidlgj** [comment]
Could you give me a little more information and an example of both schema and form?

**Comment by Dervisevic** [comment]
Closing this for now. @anurit If you do want to respond just re-open the issue.
