### ISSUE TITLE
Cannot create fields with name as array

### ISSUE THREAD

**Issue by anurit** [Textalk/angular-schema-form#258]
There are examples of complex keys and arrays.
But there is a problem to create simple things, filds with names taht are arrays as in html examples:
input type="text" name="a[some_id5]" | input type="text" name="a[some_id7]"  or select name="b[some_id2]" | select name="b[some_id4]" 
After that i can't use:
a = model.a; 
for(var element in a) { ... }

**Comment by davidlgj** [comment]
I'm not sure what your getting at here, could you give me an example?

And shouldn't it be  `name="a['some_id5']"` not ` name="a[some_id5]"`? i.e. strings inside the brackets.

**Comment by Dervisevic** [comment]
Closing this for now. @anurit If you want to respond please reopen it.
