### ISSUE TITLE
Object Editor

### ISSUE THREAD

**Issue by thekiwi** [Textalk/angular-schema-form#260]
I'm trying (and struggling) to create a simple object editor. Here's my item schema:

```json
"location": {
    "title": "Location",
    "type": "object",
    "properties": {
        "latitude": {
            "type": "number"
        },
        "longitude": {
            "type": "number"
        }
    }
}
```

At this point, I've also got the form key including a type of 'location' and a plugin (based on datepicker) that has two inputs to map to the latitude and longitude fields (with the long-term goal being a google maps pin-editor thing):

```html
<div class="form-group" ng-class="{'has-error': hasError()}">

  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>

  <input ng-show="form.key"
         style="background-color: white"
         type="text"
         class="form-control"
         schema-validate="form"
         ng-model="$$value$$.longitude" />

  <input ng-show="form.key"
         style="background-color: white"
         type="text"
         class="form-control"
         schema-validate="form"
         ng-model="$$value$$.latitude" />

  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
</div>
```

But this isn't working and I don't know where to start looking, or if this is even supported?

Any chance of some tips on how to make this work? 

Cheers!

**Comment by davidlgj** [comment]
Hi @thekiwi,

without seeing the code it's kind of hard. Generally you can do what you want inside a custom type and there is nothing in the code above that stands out. 

Make a plunkr or jsfiddle or just a gist with what you got and make a stackoverflow question and I'll have a look at it (support questions are better suited for stackoverflow).

**Comment by thekiwi** [comment]
No problem. I saw some other questions in the issues section here so I wasn't sure which you preferred. 

I've asked on stackoverflow: http://stackoverflow.com/questions/28673155/angular-schema-form-custom-object-editor and included a plunkr of the code I've got so far. 

Cheers!

**Comment by thekiwi** [comment]
I've managed to get it working, and updated the stackoverflow question in case anyone else was trying to achieve the same thing. Hopefully I'm not abusing ASF too much! :)

**Comment by davidlgj** [comment]
Yeah, I'm sorry. I've been meaning to write some kind of "issues best practices". From the beginning I didn't mind questions, but it's starting to be a bit too much so I'm trying to streamline things :)   

I just skimmed your solution, but I think it looks good!

**Comment by juanmav** [comment]
Guys I leave here the updated and working plunker.

http://plnkr.co/edit/smSDRDU86zbtIDNFKqRF?p=preview

Thanks!
JM
