### ISSUE TITLE
Required if Condition is true?

### ISSUE THREAD

**Issue by VadexFX** [Textalk/angular-schema-form#266]
Is there support for requiring a field if a condition is met? For example, in the Kitchen sink http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html If you click on Terms of Service, Soul Serial No appears. Is there a way to make that a required field? If not, what could be a work around.  Thanks!

**Comment by davidlgj** [comment]
Hi @VadexFX , just add required to the schema as you would with any field. 

The `condition` option uses a `ng-if` under the hood, so any field not visible is not part of the DOM. And schema form only validates fields in the DOM. So it should just work(™) :)

**Comment by VadexFX** [comment]
Thank you @davidlgj

**Comment by souluniversal** [comment]
davidlgj... Anyone have thoughts/ideas/perspectiv on what could be done about REAL conditional required? Case in point... even the sexy new video ("The Movie").. says "validate the data the same way on both the client and the server!". Server side schema validation can't know to ignore the required fields as the client side schema validation might.  .... data that would validate on the client won't validate against the same schema on the server... right? Hmmm.. I need lunch.. maybe I will think of more to add or a solution to this after I eat.... food for thought!

**Comment by davidlgj** [comment]
@souluniversal so it basically boils down to that you need to have a json schema that validates it, in this case probably `oneOf`, we don't support this yet though. But even then that just covers some of the use cases. `anyOf` and `oneOf` (as well as $refs) are on the todo list, but it all boils down to when I get time to do it. (or if any PR's addressing it comes in)
