### ISSUE TITLE
[Feature Request] Field Addons / Inline Forms

### ISSUE THREAD

**Issue by quietlyconfident** [Textalk/angular-schema-form#273]
For our application, we'd like:

1. The ability to style the form and/or individual fields as bootstrap inline-forms, and
2. The ability to add bootstrap input-group-addons to the fields themselves ( just icons / glyphs / etc; not other form inputs)

I think that the easiest way to do this would be to:

1. Fork ASF,
2. Add an option ( inlineBootstrap ), defaulting to false, to the globalOptions, as well as to each of the existing fields,
3. If inlineBootstrap is set globally (for the whole form) and/or locally (for the field) the decorator widget should show an inline-version of the field rather than the standard.
4. Add two options (fieldAddonLeft and fieldAddonRight) to the existing fields,
5. If an add-on option is set, then the field is displayed inside of a bootstrap input group, and the value of the option is used as the contents of the input-group-addon span.

*Most importantly* if we built this, would the maintainer be receptive to merging the changes, assuming sufficient code quality?

And, any suggestions on a better way to do it?

**Comment by quietlyconfident** [comment]
The goal BTW is to be able to attach icons to fields like so:
![screen shot 2015-02-27 at 3 57 24 pm](https://cloud.githubusercontent.com/assets/249930/6421272/18df7516-be9b-11e4-9e74-02826709313c.png)

**Comment by Dervisevic** [comment]
I can't speak for @davidlgj but if the code is clean i can't see why we wouldn't merge it.

**Comment by quietlyconfident** [comment]
See #275

**Comment by davidlgj** [comment]
Same as @Dervisevic said :)

**Comment by davidlgj** [comment]
@quietlyconfident  I'll try to merge it tomorrow... have you done any work on doing inline forms? It's an often requested feature and I was hoping to soon look into it.

**Comment by quietlyconfident** [comment]
I've made a bunch of inline forms manually (e.g. just writing HTML with
bootstrap styles) but not with ASF.  Left to our own devices we will
probably implement it within the next month or two for our application and
I'd be happy to contribute it.

-e

**Comment by plong0** [comment]
@quietlyconfident wondering if you've made any headway on the inline forms for ASF?
looking at implementing them as my next task...

**Comment by quietlyconfident** [comment]
Hello-

No, I moved onto other projects and it isn't looking like I'll get to it
anytime soon.  Go for it!

-e
