### ISSUE TITLE
Form Matrices Supported?

### ISSUE THREAD

**Issue by BKaun** [Textalk/angular-schema-form#278]
Hi,
This is a question:
Sorry if this is in the wrong place, however I didn't know where to ask.

Are matrices supported? Is there an example of how to go about doing this? Or would this have to be implemented?

Example (top portion of this following image): [http://i.imgur.com/hvEtvzx.png](http://i.imgur.com/hvEtvzx.png)

**Comment by davidlgj** [comment]
Hi @BKaun,

form matrices is not supported, but could be implemented as an add on. See the docs https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md

Its basically is the same as the "checboxes" type in line after each other, but the real question is how you want the data to be represented, an array of arrays with string?

**Comment by davidlgj** [comment]
Closing issue, but do reopen if you have further questions.
