### ISSUE TITLE
Radiobuttons inside array, adding a new element to array

### ISSUE THREAD

**Issue by Knuckles9090** [Textalk/angular-schema-form#284]
Hey, first of all, thanks for the awesome tool! I am writing, because I have a slight problem. How do I support radio buttons inside an array. Right now, despite being in different array element, the radiobuttons are grouped. For example, if I add a new array element, the selection is removed from the radiobuttons, but the value remains in the model. An example:

$scope.form = [
  {
    "key": "Test",
    "add": "New",
    "style": {
      "add": "btn-success"
    },
    "items": [
      {
          "key":"comments[].radio",
          "type":"radios-inline",
          "titleMap":[
              {"name":"Test","value":1},
              {"name":"Test2","value":2}
        ]
      }
    ]
  }
]
$scope.schema = {
  "type": "object",
  "title": "Comment",
  "properties": {
    "Test": {
      "type": "array",
      "maxItems": 5,
      "items": {
        "type": "object",
        "properties": {
          "radio": {
            "title": "Radio",
            "type": "string",
            "enum":[1,2]
          }
        }
      }
    }
  }
}

**Comment by davidlgj** [comment]
I believe this is because they get the same `name` attribute which is fixed with PR #267, which is merged to the development branch and should end up in next release.

**Comment by Knuckles9090** [comment]
Yeah, that seems to be fixing the issue! Thanks for the response, as well as for the tool!
