### ISSUE TITLE
restrict directive sf-decorator to attribute instead of element

### ISSUE THREAD

**Issue by ssolida** [Textalk/angular-schema-form#285]
Hi guys !
working on a semantic-ui (http://semantic-ui.com/) decorator and would like to know if there would be a way to declare the directives sf-decorator as attribute instead element ?

Semantic-ui is  relying a lot on elements order ... and having sf-decorator element always surrounding my fields is killing my design

In other terms, I would like to have this :
```
<div sf-decorator class="ui input"><input type="text"></div>
```
instead of this :
```
<sf-decorator>
  <div class="ui input"><input type="text"></div>
</sf-decorator>
```

**Comment by davidlgj** [comment]
Hi @ssolida,

Changing to an attribute is easy, more or less a search and replace, but actually getting rid of one level of elements is a lot harder.

I.e. just changing `<sf-decorator>` to `<div sf-decorator>` is easy, but the you would end up with:
```html
<div sf-decorator>
  <div class="ui input"><input type="text"></div>
</div sf-decorator>
```

Not: 
```html
<div sf-decorator class="ui input"><input type="text"></div>
```

Would that be ok?

**Comment by ssolida** [comment]
sorry, in fact the problem is on the upper level, just below  "form" tag, I would like to have  __bootstrap-decorator__ as attribute directive instead of en element

--html
<form sf-schema="details_schema" sf-form="details_form" sf-model="details_model">
    <bootstrap-decorator form="schemaForm.form[0]" class="ng-scope">...</bootstrap-decorator>
    <bootstrap-decorator form="schemaForm.form[1]" class="ng-scope">..</bootstrap-decorator
    <bootstrap-decorator form="schemaForm.form[2]" class="ng-scope">..</bootstrap-decorator>
</form>
--

Also Search&replace string doesn't work in this case as the bootstrap-decorator is created dynamically in bootstrap-decorator.js

--javascript
 decoratorsProvider.createDecorator('bootstrapDecorator', {...
--

**Comment by davidlgj** [comment]
Is this what you want? 
```html
<form sf-schema="details_schema" sf-form="details_form" sf-model="details_model">
    <div bootstrap-decorator="schemaForm.form[0]" class="ng-scope">...</div>
    <div bootstrap-decorator="schemaForm.form[1]" class="ng-scope">..</div>
    <div bootstrap-decorator="schemaForm.form[2]" class="ng-scope">..</div>
</form>
```

That is as a said above doable. Just need to change a couple of places where they are generated as elements to div's with attributes. (directives/schema-form.js and all templates that render sub parts, tabs, fieldset, section, array etc)

A semantic ui decorator would be awesome btw :)

**Comment by anilkokate2009** [comment]
how to add submit button on sf-schema-form in anguar 6 and how to route the link on submit page
