### ISSUE TITLE
Uncaught exception for valid JSON schema

### ISSUE THREAD

**Issue by perqa** [Textalk/angular-schema-form#286]
Elaborating a bit from the example given here on Github, I replaced the schema with a custom one. I have converted the below Javascript object to JSON and validated the schema against http://jsonschema.net/. However, that schema breaks the library code with error message:
```
TypeError: Cannot read property 'key' of undefined
    at http://localhost:9000/bower_components/angular-schema-form/dist/schema-form.js:782:16
```
Library code:
```
      return postProcessFn(form.map(function(obj) {

        //handle the shortcut with just a name
        if (typeof obj === 'string') {
          obj = {key: obj};
        }

        if (obj.key) {  // *This is where it breaks - the object is undefined*
          if (typeof obj.key === 'string') {
            obj.key = sfPathProvider.parse(obj.key);
          }
        }
```

Schema definition (as Javascript object) in app code:
```
   $scope.schema = {
    $schema: "http://json-schema.org/draft-04/schema#",
        type: "object",
        properties: {
            PKG: {
              id: "PKG",
              type: "array",
              items: [
                {
                  id: "0",
                  type: "object",
                  properties: {
                    name: {
                      id: "name",
                      type: "string"
                    },
                    id: {
                      id: "id",
                      type: "integer"
                    },
                    price: {
                      id: "price",
                      type: "integer"
                    },
                    description: {
                      id: "description",
                      type: "string"
                    }
                  }
                }
                ]
            }
          }
    };
```

In the app, I want to read the schema from a file. The following schemas have both been validated against http://jsonschema.net. I can read them both into Angular as Javascript objects. The first, simple one works. The second breaks the code. Both are valid schemas...?

JSON schema extracted and converted from Github repository example:
https://drive.google.com/file/d/0B2JNWcAU8YFLaHNPdWNpYlJfVjQ/view?usp=sharing

Custom JSON schema:
https://drive.google.com/file/d/0B2JNWcAU8YFLX2F0dkhqUWRRUFU/view?usp=sharing

**Comment by davidlgj** [comment]
Oh that is an ugly error, and kind of misleading. The problem is that schema form only supports array that have a schema as the value under "items" not an array of schemas.

See the docs: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#array

This is because it is the validation is very different and would require a very different form field than the drag and drop array we have today. 

Here is the relevant part of the spec:
```
8.2.3.2.  If "items" is an array

In this situation, the schema depends on the index:

    if the index is less than, or equal to, the size of "items", the child instance must be valid against the corresponding schema in the "items" array;

    otherwise, it must be valid against the schema defined by "additionalItems".
```

If this is really what you want please think about how that form field should look and come with some suggestions on how to solve it and we can make this a feature request. Otherwise feel free to close the issue :)

**Comment by perqa** [comment]
Yes, sorry! I just realised I haven't adapted my form to the new schema.... you can ignore my bug report. Thanks for the feedback. If I come up with something I will open a new feature request instead.
