### ISSUE TITLE
Accessing third-party directives from a custom decorator

### ISSUE THREAD

**Issue by oppodeldoc** [Textalk/angular-schema-form#293]
Hi, thanks for everyone's great work on this project!  I'm in the process of trying to write an add-on using [TextAngular](https://github.com/fraywing/textAngular) as a wysiwyg. It is working pretty well out of the box, but there are a couple of useful  TextAngular directives that I'd like to use, and I simply have no idea how to build that workflow into a custom decorator. TA offers a "taFileDrop" directive that allows handling of files dropped directly onto the editor, calling a function in the scope where (I think) you can pass in the DOM element object as $html. The very simple template file I'm working with looks like this:

```html
<div class="form-group" ng-class="{'has-error': hasError()}">
  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>
  <div
    text-angular
    ta-file-drop="fileDropHandler($html)"
    ng-model="$$value$$"
    schema-validate="form"
  ></div>
  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
</div>
```

My question is, within this custom add-on, I'd love to add a service that handles the file itself when it is dropped (allowing for format/size checking, etc.) but I have no idea how to call fileDropHandler from here within my add-on.  Any help/suggestions on best-practices here would be appreciated.  Thanks!

**Comment by davidlgj** [comment]
Hi @oppodeldoc 

I would add a directive (or a controller, but a directive is nicer), that sets on scope the functions you need and can use any service you need. 

Something like:
```html
<div drop-handler class="form-group" ng-class="{'has-error': hasError()}">
  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>
  <div
    text-angular
    ta-file-drop="fileDropHandler($html)"
    ng-model="$$value$$"
    schema-validate="form"
  ></div>
  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
</div>
```
```js
angular.module('myModule').directive('drop-handler', ['awesomeService', function(awesome) {
  return {
     scope: false,
     link: function(scope, element, attrs) {  
     
        scope.fileDropHandler = function(html) {
            ....do stuff here, call services etc, use scope.ngModel.$setValidity to change validation etc.
         }
     } 
  }
}])
```

Hope that helps!

**Comment by oppodeldoc** [comment]
I think a directive is a great option here, looks nice and clean and testable. Thanks for laying it out so clearly (and quickly), and great job on this crazy machine!
