### ISSUE TITLE
Is it possible to use data loaded after the schema form is initialized?

### ISSUE THREAD

**Issue by whoadave** [Textalk/angular-schema-form#298]
For example, if I had one dropdown to choose the make of a car, and a second to choose the model, but I wanted to load the model options from the server depending on which make was selected, would that be possible?

Right now if I try to set the `titleMap` for a form field to an empty array on the scope that I'll update later, it doesn't actually bind to that scope property, and just uses the empty array for the titleMap. Might there be another/better way to achieve what I want? Thanks!

**Comment by davidlgj** [comment]
See the docs https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#updating-form

**Comment by whoadave** [comment]
Ah I missed that, thanks!
