### ISSUE TITLE
Custom Filters?

### ISSUE THREAD

**Issue by orderofout** [Textalk/angular-schema-form#302]
Is there an easy way to pass a custom filter to a textfield?

For example, if I want to format a phone number to 000-000-0000 or a ssn to xxx-xx-xxxx?

I know the pattern to validate the fields, but I'd like to format it as the user types.

Any suggestions are appreciated. Thanks in advance!

**Comment by Knuckles9090** [comment]
I believe you could just use the onChange functionality. I am not aware if ready made filters exist.

**Comment by davidlgj** [comment]
I'm not sure if it will help, but in the development branch there is a new feature that exposes the `ngModelController` of a field to the form definition so you can set `$parsers` or `$formatters`, that might work, but I haven't tried it.

**Comment by Dervisevic** [comment]
Try that @orderofout If it doesn't work open this up again.
