### ISSUE TITLE
Turning off feedback?

### ISSUE THREAD

**Issue by shawnss** [Textalk/angular-schema-form#303]
Is there a way to turn off feedback (has-success, etc.). I am trying to dynamically create a form and don't have any validation. User types new or change value of fields and saves the data. As a side, I like to highlight the controls when user changes the values.

**Comment by davidlgj** [comment]
You can turn off the inline feedback icons https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#inline-feedback-icons

And while you can't turn off the feedback classes you can use CSS to remove the styling that bootstrap gives as a default.

**Comment by shawnss** [comment]
Thanks David, I am setting the feedback to false, but also wanted to turn off the highlighting as well.
