### ISSUE TITLE
Examples fail on new site with Https

### ISSUE THREAD

**Issue by msc654** [Textalk/angular-schema-form#307]
The demo link from your new website loads the page in https. This is causing the more advanced examples that call other libs to fail.

Mixed Content: The page at 'https://textalk.github.io/angular-schema-form/examples/bootstrap-example.html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-2.1.1.min.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap-example.html:1 Mixed Content: The page at 'https://textalk.github.io/angular-schema-form/examples/bootstrap-example.html' was loaded over HTTPS, but requested an insecure script 'http://cdn.jsdelivr.net/g/jquery.ui@1.10'. This request has been blocked; the content must be served over HTTPS.

**Comment by Dervisevic** [comment]
This has been fixed, we now use // instead of hardcoding http:// so it will load it over https if you surf in on https.
