### ISSUE TITLE
Invalid type expected number

### ISSUE THREAD

**Issue by AlexAlbala** [Textalk/angular-schema-form#309]
Validation message error in (apparently) random cases when using a type: Number schema field.

The schemaForm throws a validation error saying that expects a number when actually it is a number !

This occurs in development branch, I go back to master branch and works perfectly

Thank you

**Comment by davidlgj** [comment]
@AlexAlbala thanks for testing the development branch, I'll look into it right away

**Comment by davidlgj** [comment]
OK, I didn't get any error until I tried to submit the form and validated using 'schemaFormValidate' event, 
then it went bonkers, the problem was that it validated using the `ngModel.$viewValue` instead of the `ngModel.$modelValue` so I think that was the bug!

**Comment by davidlgj** [comment]
Forgot to mention this issue in the commit: 7f434c67022a6a21e4f78baa8b842d8e0bdd4cbe

**Comment by davidlgj** [comment]
Closing this now that 0.8.0 is out, but please re-open if you still get problems.

**Comment by dhiraj** [comment]
![failing number validator](https://cloud.githubusercontent.com/assets/43901/10477816/f202c052-7276-11e5-91bd-758ec001cfa1.png)

My bower.json has `"angular-schema-form": "~0.8.12",`

**Comment by manusa** [comment]
I'm experimenting the BUG too with version 0.8.12

**Comment by manusa** [comment]
It was my fault, field was incorrectly set as type "text" in form definition and as "number" in schema.
