### ISSUE TITLE
updateOn error with custom type

### ISSUE THREAD

**Issue by PhilBroadbent** [Textalk/angular-schema-form#312]
Hi - I'm trying to create my own type but having a problem....

My form:

    {
      fieldName: 'test',
      title: 'Phils Test',
      type: 'string',
      uiType: 'multiselect',
      format: 'multiselect',
      required: false
    }

fieldname maps to Key
uiType maps to type
Thus my form becomes:
    key: "test"
    type: "multiselect"

When I come into my js config file with my variable 

    var multiselect = function(name, schema, options) {
      if (schema.type === 'string' && schema.format === 'multiselect') {
        var f = schemaFormProvider.stdFormObj(name, schema, options);
        f.key  = options.path;
        f.type = 'multiselect';
        options.lookup[sfPathProvider.stringify(options.path)] = f;
        return f;
      }
    };

options does NOT contain options for my form element.
Actualy i've just found that in some calls it does - thing is, it gets  called 16 times?!?

    global: Object
    ignore: Object
    lookup: Object
        ['regions']: Object
        ['scorecard']: Object
        ['system']: Object
        ['transactiondate']: Object
    __proto__: Object
    path: Array[1]
    required: undefined
    __proto__: Object

Thus options doesn’t get set…so I see:

`TypeError: Cannot read property 'updateOn' of undefined`
``    at new ngModelOptionsDirective.controller (angular.js:23812)``
`    at Object.invoke (angular.js:4203)`
`    at $get.extend.instance (angular.js:8493)`
`    at angular.js:7739`
`    at forEach (angular.js:331)`
`    at nodeLinkFn (angular.js:7738)`
`    at compositeLinkFn (angular.js:7117)`
`    at publicLinkFn (angular.js:6996)`
`    at scorecards.controller.js:83`
`    at processQueue (angular.js:13248)`

Note that my html file is copied from datepicker, but replacing the input with something simple:

`<input ng-show="form.key"`
   `    style="background-color: white"`
    `   type="text"`
    `   class="form-control"`
     `  schema-validate="form"`
       `ng-model="$$value$$"/>`

Also note my schema is:

    properties: Object
    regions: Object
    scorecard: Object
    system: Object
    test: Object
        fieldName: "test"
        format: "multiselect"
        required: false
        title: "Phils Test"
        type: "string"
        uiType: "multiselect"
    __proto__: Object
    transactiondate: Object

Can anyone suggest what's going on please?

**Comment by davidlgj** [comment]
I'm not sure I follow you, what is the top form example? 

Can you elaborate what you mean with "options does NOT contain options for my form element:"? 
What is it you think should be in options? 

This part of the code is only there to create a default form definition object from the schema
that is *later* merged with your supplied form definition object. 
```js
var multiselect = function(name, schema, options) {
  if (schema.type === 'string' && schema.format === 'multiselect') {
    var f = schemaFormProvider.stdFormObj(name, schema, options);
    f.key  = options.path;
    f.type = 'multiselect';
    options.lookup[sfPathProvider.stringify(options.path)] = f;
    return f;
  }
};
```
You can actually skip it entirely if you want, it's just that autogenerating a form directly from a schema with your type that stops working, i.e. you need to set `type: "multiselect"` in your form definition.  

The updateOn error comes from angular, it doesn't like you sending an `undefined` value to the `ngModelOptions` directive. If possible, could you show me the actual code? like a gist or a plunkr or something.

**Comment by davidlgj** [comment]
How does your call to `schemaFormDecoratorsProvider.addMapping()` look?

**Comment by PhilBroadbent** [comment]
Okay sorry for confusion. The top "form" is actually my JSON definition (although it doesn't look JSON, but when it comes from the backend it is)...
This "definition" is used to build both the form, and the schema.
As I said above, fieldName maps to "key", and uiType maps to "type" to create the form, and the other fields are used for schema.

What I meant by "options does NOT contain options" is that the options object contained an entry for  only 4 of my form fields, and not my 5th - but in my edit I added that actually it is there *sometimes* - if I put a breakpoint in there I see this function called 16 times!?

`schemaFormDectoratorsProvider.addMapping()` looks like:

      schemaFormDecoratorsProvider.addMapping(
        'bootstrapDecorator',
        'multiselect',
        'client/components/schemaform-addons/directives/multiselect.html'
      );
      schemaFormDecoratorsProvider.createDirective(
        'multiselect',
        'client/components/schemaform-addons/directives/multiselect.html'
      );

Not sure I can show - there's a lot of code and I don't know how to use plunkr! Need to learn!

I'm gonna revert my code and start anew I think - I'm still getting this updateOn issue despite not having the extra element defined....I did upgrade from 10 to 13 though so could be the issue for that - I will try.

**Comment by davidlgj** [comment]
Hmmmm... you mean the `options.lookup`? 16 times sounds a lot...  I'll have to look into that.

Btw `schemaFormDecoratorsProvider.createDirective()` is an undocumented (not in the [extending docs](https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md)) and not recommended to use, but it shouldn't cause any problems.

Anyways a couple of things too look out for:
1) If a form object has a key that doesn't match the schema you still get an empty input, but the it's broken and often contains the placeholder `{{placholder}}` , this also trigger the updateOn error.
2) form object "type" is matched against the the mappings available, if none is found it will use `default.html` and that has a ngModelOptions, so check that you are actually getting your add-on template.

**Comment by PhilBroadbent** [comment]
Yeah the var multiselect function gets called 16 times and that options var didn't have my element in.

Anyway, I've reverted code and no longer see updateOn, so must have fat fingered somewhere.
Now what I see though if I add in a new part of the definition is that for some reason my controller is instantiated twice (causing angular and highcharts reload warning) which is weird.

I have removed schemaFormDecoratorsProvider (I had it because that's what's in DatePicker). 

So now this is all my relevant code:

my service:

        {
          fieldName: 'philtest',
          title: 'Phil Test',
          type: 'string',
          uiType: 'multiselect',
          required: false
        }

part of mapper function so you can see what I mean:

          var formDefinition = {
            'key': schemaDefinition.fieldName,
            'onChange': schemaDefinition.onChange
          };
          var uiType = {
            'select': {
              type: 'select'
            },
            'multiselect': {
              type: 'multiselect'
            },

multiselect.js (I can have a second config block...right...additional to the one in app.js?)

    angular.module('fullstackAngularApp').config(
      ['schemaFormProvider', 'schemaFormDecoratorsProvider', 'sfPathProvider',
        function(schemaFormProvider,  schemaFormDecoratorsProvider, sfPathProvider) {

          schemaFormDecoratorsProvider.addMapping(
            'bootstrapDecorator',
            'multiselect',
            'client/components/schema-form-addons/multiselect/multiselect.html'
          );
       }
      ]);

and multiselect.html:

    <div class="form-group {{form.htmlClass}}" ng-class="{'has-error': hasError()}">
      <label class="control-label" ng-show="showTitle()">{{form.title}}</label>
    
      <div ng-class="{'input-group': (form.fieldAddonLeft || form.fieldAddonRight)}">
        <span ng-if="form.fieldAddonLeft"
              class="input-group-addon"
              ng-bind-html="form.fieldAddonLeft"></span>
        <input ng-show="form.key"
               style="background-color: white"
               type="text"
               class="form-control"
               schema-validate="form"
               ng-model="$$value$$"/>
        <span ng-if="form.fieldAddonRight"
              class="input-group-addon"
              ng-bind-html="form.fieldAddonRight"></span>
      </div>
      <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}        </span>
    </div>


All I see is warnings about reloading controller, but there is only the previously defined 4 elemnts, and my new element is not there.

Any ideas please? Been at this for hours!

**Comment by davidlgj** [comment]
> multiselect.js (I can have a second config block...right...additional to the one in app.js?)

Oh yes, thats fine.

Warnings about reloading controller? Copy paste them for me will you? 

And as I said earlier, how are you loading the template? Because if you aren't pre-compiling it to JS your path might be the problem, check the neworks tab in developer tools of your browsers if you're ajax loading it and see that it is the correct template.

**Comment by davidlgj** [comment]
Otherwise your code looks legit!

**Comment by PhilBroadbent** [comment]
Reloading errors:

    GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
    jquery.js:7784 Synchronous XMLHttpRequest on the main thread is deprecated because of its   detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
    VM83518:26293 WARNING: Tried to load angular more than once.
    VM83544:13 Uncaught Highcharts error #16: www.highcharts.com/errors/16

Interesting - I can't see the call in networks tab (although there's a lot so maybe I missed). But  my express server says:

Express server listening on 9000, in development mode
GET /dataquality/scorecards/drilldown 304 11ms
GET /client/components/schema-form-addons/multiselect/multiselect.html 304 1ms

I didn't pay attention to 304 as I always get that drilldown message there which works fine...but from reading about it it's an error? Unsure of how to load it if this is a problem.

**Comment by davidlgj** [comment]
`WARNING: Tried to load angular more than once.` you get this because you have two `angular.bootstrap()` calls (or I guess two `ng-app` calls).

You can get this message if your server answers with the entire page instead of just the template on the `GET /client/components/schema-form-addons/multiselect/multiselect.html 304 1ms` request. This can happen if you express routes aren't configured correctly.

**Comment by PhilBroadbent** [comment]
Okay the html is in the same folder so I just changed the path - now I see the call, however the response doesn't have my div's on...just lots of bower injected source links

**Comment by davidlgj** [comment]
For add-ons its a good idea to precompile the templates to js (it essentially just a function that adds the template to $templateCache)

In schema form we use:
https://www.npmjs.com/package/gulp-angular-templatecache

This way you don't need to configure any paths on the server. It's also easier to distribute and use by others since they don't need to configue any routes on their server.

**Comment by PhilBroadbent** [comment]
I will have to look into that!
For the time being, I just played around with the path until I the response was the actual HTML, and now I see the element! So now I will try to make a useful component...
Thanks a lot for your help!

**Comment by davidlgj** [comment]
No problem :-) I'll close this issue for now.
