### ISSUE TITLE
Info needed: Schema's `format` property

### ISSUE THREAD

**Issue by benoror** [Textalk/angular-schema-form#317]
Hello! In the [kitchensink example](http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html) some fields have a `format` property:

    "date": {
      "title": "Date of party",
      "type": "string",
      "format": "date"
    },

	"eyecolor": {
	  "type": "string",
	  "format": "color",
	  "title": "Eye color",
	  "default": "pink"
	},

    "invitation": {
      "type": "string",
      "format": "html",
      "title": "Invitation Design",
      "description": "Design the invitation in full technicolor HTML"
    },

Is there **documentation** for it?

Thanks and keep the great work!

**Comment by benoror** [comment]
I can see you use [third-party-addons](http://textalk.github.io/angular-schema-form/#third-party-addons) in the kitchensink, but still would like to know the difference between setting **type & format in schema versus type in form**

**Comment by Dervisevic** [comment]
When you write a addon you can choose to specify both, so a type in form can be something like datepicker, and thats what will be shown. You can also specify a corresponding format for the schema, so format date can correspond to the type datepicker.

You can see the example here: (row 6 and 9)
https://github.com/Textalk/angular-schema-form-datepicker/blob/master/src/bootstrap-datepicker.js

I think there is additional information here: https://github.com/Textalk/angular-schema-form/blob/development/docs/extending.md

**Comment by davidlgj** [comment]
Thanks! 

"format" is part if the json schema spec found here: http://json-schema.org/ it governs custom validation, several addons also use them to signify form field defaults.

The datepicker, colorpicker and tinymce addon have the code and the documentation in this case. See schemaform.io for list of add-ons and their repos

**Comment by benoror** [comment]
Cool thanks!

Anyway I think it could be worthy to include a little information in index.md regarding that property.

Regards and kudos!

**Comment by davidlgj** [comment]
The docs has a lot on schema and form types as well

https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#form-defaults-in-schema
