### ISSUE TITLE
Condition on array

### ISSUE THREAD

**Issue by deyceg** [Textalk/angular-schema-form#320]
Can't find any specific reference to it in the docs, but is it possible to apply a condition to an entire array?

```
[
  {
   key: "someValue"
  },
  {
   key: "someArray",
   items: [ ... ]
   condition: "model.someValue === 'foo'"
  }
]
```

**Comment by stramel** [comment]
@deyceg You should be able to specify a `section`

```js
var form = [{
  type: 'section',
  condition: 'index > 1',
  items: [{
    type: 'checkbox',
    ...
  }, {
    type: 'submit',
    ...
  }]
};
```

**Comment by deyceg** [comment]
@stramel Great stuff! Let me try it out

**Comment by deyceg** [comment]
I wrapped my array form def in a section with a condition. Worked like a charm
