### ISSUE TITLE
Input FILE type

### ISSUE THREAD

**Issue by ravivit9** [Textalk/angular-schema-form#323]
Hi,

I have read through old tickets for implementation of introducing FILE type to upload binary files.  But couldn't get a clear idea how to implement via $scope.form.

I understand that schemaFormDecoratorsProvider need to be updated to introduce custom input types.  But not sure whether this will get overwritten when I update the a-s-f library?

**Comment by davidlgj** [comment]
Put your add-on in a separate repo, not in a fork och schema form. Check out one of the add-ons on schemaform.io to get a feel for it. (and of course the [docs on extending](https://github.com/Textalk/angular-schema-form/blob/development/docs/extending.md) if you haven't found them)
