### ISSUE TITLE
Asynchronous data loading to select list

### ISSUE THREAD

**Issue by cfgj** [Textalk/angular-schema-form#331]
Hey,
I have a problem with using angular schema form and ajax. Can you tell me how can I dynamically load data to select list? Is it possible?
```javascript
{
    title: 'select list',
    type: 'string',
    enum: [] // I need set this field via ajax.
}
```

Thank you for any help you can provide.

**Comment by benoror** [comment]
Did you check <http://schemaform.io/#third-party-addons> ?

I personally prefer Angular UI, therefore [UI Select](https://github.com/networknt/angular-schema-form-ui-select)

**Comment by Dervisevic** [comment]
I mean if you just want to add data to the select, just make the ajax request, get the data and put the values into the schema, shouldn't really be anything more to it? Unless i'm reading the question wrong.
