### ISSUE TITLE
Decorators not decorating after "schemaFormRedraw"

### ISSUE THREAD

**Issue by thomask** [Textalk/angular-schema-form#337]
Hi I want to be able to change the form dynamically.

This is my test code:

`````
$http.get(formUrl).success(function(data) {
    $scope.schema = data.schema;
    $scope.form = data.form;

    setTimeout(function(){
      $scope.form[2].title = "SOMETHING ELSE";
      $scope.$broadcast('schemaFormRedraw');
    }, 3000)
});
`````

So initially everything goes as expected:

`````
<form sf-schema="schema" sf-form="form" sf-model="item" class="ng-pristine ng-valid ng-isolate-scope">
    <bootstrap-decorator form="schemaForm.form[0]" class="ng-scope"> << html here >> </bootstrap-decorator>
    <bootstrap-decorator form="schemaForm.form[1]" class="ng-scope"> << html here >> </bootstrap-decorator>
    <bootstrap-decorator form="schemaForm.form[2]" class="ng-scope"> << html here >> </bootstrap-decorator>
</form>
`````

However after the timeout, when I update the form object and broadcast the `schemaFormRedraw` event, I get empty `bootstrap-decorator`nodes:

`````
<form sf-schema="schema" sf-form="form" sf-model="item" class="ng-pristine ng-valid ng-isolate-scope">
    <bootstrap-decorator form="schemaForm.form[0]" class="ng-scope"></bootstrap-decorator>
    <bootstrap-decorator form="schemaForm.form[1]" class="ng-scope"></bootstrap-decorator>
    <bootstrap-decorator form="schemaForm.form[2]" class="ng-scope"></bootstrap-decorator>
</form>
`````

When I update the model. The form will get redrawn again though. I tried to debug it, but I can't really follow where the update should take place.

Any clues?

**Comment by davidlgj** [comment]
Hi @thomask, try using `$timeout` or add a `$scope.$apply()` after the schema form event.

**Comment by stramel** [comment]
@thomask @davidlgj I would use `$interval` instead of `$timeout` because `$timeout` has been known to cause issues with protractor testing.

**Comment by thomask** [comment]
Thanks that fixed it! Only used the timeout for testing purposes. Spent half a day trying to fix this :s
