### ISSUE TITLE
Input Array with hidden id's

### ISSUE THREAD

**Issue by plong0** [Textalk/angular-schema-form#340]
I am wondering what the best approach is to render an array where each entry has an id field + the normal schema describing it.

So for example, I have a schema like:
```
"test": {
	"title": "Test",
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"field1": { "type": "string" },
			"field2": { "type": "string" }
		}
	}
}
```

When I load the test array, each entry would look like this: `{ id: <unique_id>, field1: "my first string", field2: "another string!" }`

I would also like it to work for more simple arrays like:
```
"test1": {
	"title": "Test",
	"type": "array",
	"items": { "type": "string" }
}
```
Where the same thing, I get an array where each entry looks like: `{ id: <unique_id>, test1: "the value!" }`

I have found the way of: `{ "key": "test1", "items": [ { "key": "test1[].id", "type": "hidden" }, "test1[].test1" ] }` but I feel like there might be a way where I don't need to configure my form so precisely?  (I'd prefer to just have `{"key": "test1"}` and because it's an array, it automatically handles the id as hidden)

I am thinking something along the lines of overwriting the array decorator somehow to automatically render the id as hidden, but I am not sure what the correct way to do that is.

**Comment by plong0** [comment]
Solved it the simple way by just adding the id into the schema.

I did make a small hack where I update the $templateCache's `directives/decorators/bootstrap/array.html` to replace the copyWithIndex($index) with my own hideArrayId($index) which gets the formDefCache from copyWithIndex and makes any items with key 'id' as hidden.

**Comment by davidlgj** [comment]
Good that you solved it!  I was going to suggest just adding the ids afterwards just before you do what you do on submit :)
