### ISSUE TITLE
Config option to wipe the model when a condition is no longer fulfilled?

### ISSUE THREAD

**Issue by jbsaff** [Textalk/angular-schema-form#344]
I'd like wipe out user input from the model when the condition on a form field is no longer met. Currently the model is updated when a condition is met, but not when it no longer applies. Is there an option that I'm missing? A plain angular ng-if seems to do what I want, but that's because the form only submits elements in the DOM. I'd like to just take the schema-form model as my finished form response and go from there.

Any pointers would be greatly appreciated. Thanks!

**Comment by davidlgj** [comment]
There has been some discussion on this over at https://github.com/Textalk/angular-schema-form/issues/204, so check that out. 

But he TL;DR; is that it's a good idea, at least to have it optionally.

**Comment by jbsaff** [comment]
That's exactly what I'm thinking of. Thanks for the pointer. Sorry I missed the open discussion.

**Comment by jbsaff** [comment]
I'm not a JS or AngularJS guy by trade (yet!), but I wanted to take a stab at solving my own problem. I had a couple of other form types/decorators I wanted, so I slipped in an extension to the schema-validate directive. https://github.com/jbsaff/angular-schema-form-multiselect for anyone interested.  It's not configurable yet, but if I make progress in that direction I'll submit a PR.

**Comment by jbsaff** [comment]
Improved my solution and submitted it as a new feature via #371. I'm closing this issue because my initial question was answered and any follow-up can occur in the PR thread.
