### ISSUE TITLE
Array of checkbox need initial

### ISSUE THREAD

**Issue by owlgraphic** [Textalk/angular-schema-form#347]
I have my form model variable is the_obj.
and in my schema:
{
 devices:{
                type: 'array',
                title: 'devices',
                items: {
                    "type": "string",
                    enum: ['Mobile','Tablet','Desktop']
                }
            }, 
}

Problem is if i have empty *the_obj* loaded to form, when i check those checkbox i got error in my console, and form submit without *devices* array. I fixed this by init my *the_obj* with empty array : { devices:[] } but in many cases I can't set empty array to the object  load to form.

**Comment by Dervisevic** [comment]
ASF creates the structure for you in the model, i tried your schema in the [examples page](http://schemaform.io/examples/bootstrap-example.html) and it worked without any issue, not sure why that is happening for you. 

The schema but in JSON so you can paste in and try.
```javascript
{
  "type": "object",
  "properties": {
    "devices":{
      "type": "array",
      "title": "devices",
      "items":
        {
          "type": "string",
          "enum": ["Mobile","Tablet", "Desktop"]
        }
      } 
    }
  }
```

**Comment by marcussaad** [comment]
@Dervisevic, what should I do when I'm able to see that the binding between the schema definition and model attribute was done, but still not being able to get the checked answers from the checkboxes?

My schema is working on the example page, but not on my application. What I have is:

On the form
```
sf-model="modelData"
```

On the controller

```
$scope.modelData = {};
```

And to display I'm using the same function as in the example
```
$scope.pretty = function(){
        return typeof $scope.modelData === 'string' ? $scope.modelData : JSON.stringify($scope.modelData, undefined, 2);
    };
```

What is being displayed is this, even with checked inputs:
```
{ "question1": [], "question2": [], "question3": [], "question4": [] } 
```
