### ISSUE TITLE
Query: Is there a way to refresh portion of form ?

### ISSUE THREAD

**Issue by shevanid** [Textalk/angular-schema-form#348]
Use Case : Populate enum of "cities" field based on value selected in "state" field ?

Currently, I am using "onChange" : "updateCityKeyList(modelValue)" in form schema for "state", but form is not reflecting.

**Comment by davidlgj** [comment]
Hi @shevanid. No, not part of it, bu you can redraw the entire form by broadcasting the event `schemaFormRedraw`, [see the docs](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#updating-form)

Another way is to use an add-on, checkout schemaform.io for a complete list but try out https://github.com/OptimalBPM/angular-schema-form-dynamic-select and see if that works for you.
