### ISSUE TITLE
Retrieving value of fields

### ISSUE THREAD

**Issue by marcussaad** [Textalk/angular-schema-form#372]
So, I've been playing with a-s-f for a while but haven't fully figured it out yet. What is sf-model used for? How can I retrieve the values of the inputs since each field isn't being binded using ng-model?

**Comment by jbsaff** [comment]
If you haven't seen it already, the example page http://schemaform.io/examples/bootstrap-example.html was really helpful to me. The value you give sf-model is the variable name for the object that will hold the form response. So if you have sf-model defined as "model", you can put that in double curly braces in your web page and see the current state if the model object.

**Comment by marcussaad** [comment]
Hey @jbsaff, I've seen that. My "model" as to say, never changes. All I'm working with are checkboxes, but I can't find seem to get which were checked by debugging "model" variable. I'll give that another go.

**Comment by marcussaad** [comment]
The problem is happening on my custom directive. Still trying to figure it out. @jbsaff thanks for that tip, it helped me debugging.

**Comment by jbsaff** [comment]
@marcussaad Glad it helped.
