### ISSUE TITLE
Missing css class for textarea labels

### ISSUE THREAD

**Issue by LongHairedHacker** [Textalk/angular-schema-form#373]
Hi,
I just noticed a minor in consistency in the boostrap decorators.
The labels for textareas do not have the control-label css class set.
As a result the labels do not turn green or red if the field is valid or invaid.

![labels](https://cloud.githubusercontent.com/assets/1888799/7393417/db581cf2-ee8d-11e4-89fb-94281b93a284.jpg)

**Comment by marcussaad** [comment]
Confirming that it lacks the control-label class.

If you want to make a pull request @LongHairedHacker, the file is:

https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/textarea.html#L2

**Comment by Dervisevic** [comment]
Thanks, it'll be included in the next release.
