### ISSUE TITLE
checkboxes are not validated on change.

### ISSUE THREAD

**Issue by punknroll** [Textalk/angular-schema-form#377]
Hi, 

when i have required checkboxes the validation message should go away when I click on one checkbox not just after submission.

http://schemaform.io/examples/bootstrap-example.html#/fe1bc2901ad04983c223

Is there another way to trigger that?

greetz

**Comment by davidlgj** [comment]
I think you might have  been bitten by this bug, https://github.com/Textalk/angular-schema-form/pull/370

**Comment by punknroll** [comment]
Hi, I checked out the development branch where #370 is fixed but validation doesn't work as well. When I uncheck the first item in my gist the form becomes invalid but then there is no validation anymore.

**Comment by punknroll** [comment]
I made a plunker for this problem:
http://plnkr.co/edit/r0ib4Knh738KjCL6jnBE?p=preview

**Comment by davidlgj** [comment]
I was totally wrong in thinking #370 should fix it... but it should be fixed now in development branch, please try it out if you have time.

**Comment by punknroll** [comment]
Yes, it is fixed now. Thank you very much.
