### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by bibidon** [Textalk/angular-schema-form#379]
How I can used attribute placeholder at the schema ?
And how to establish default value for tag select ?

**Comment by Dervisevic** [comment]
In the form definition, just add the placeholder to the definition. I prepared an example for you here: http://schemaform.io/examples/bootstrap-example.html#/d5d18c8a1341a2c713ec

**Comment by bibidon** [comment]
Thank you but i don't want to use form only schema and form ["*"] I found how to do http://schemaform.io/examples/bootstrap-example.html#/9ff9d0497cbc365f18e9

**Comment by Dervisevic** [comment]
You can still use the form stuff in the schema with x-schema-form: Example: http://schemaform.io/examples/bootstrap-example.html#/610b43b6c323124c7e18

**Comment by bibidon** [comment]
Thanks you for the quick response
