### ISSUE TITLE
does array have to always show one initial item and then be saved as [null]?

### ISSUE THREAD

**Issue by israelidanny** [Textalk/angular-schema-form#384]
I find the default behaviour a bit messy. I have an array where unless I specifically want to add something, I don't wanna see anything but the add button. 

Is there a way to default the form to a state where empty arrays don't show any items, as opposed to the default behaviour of showing one empty item?

**Comment by Dervisevic** [comment]
Yes, under the [array section](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#array) of the documentation it states:

> *By default the array will start with one undefined value so that the user is presented with one a form, to suppress this set the attribute startEmpty to true.*
