### ISSUE TITLE
Manual Form insertion does not work when classes are applied to the containing div

### ISSUE THREAD

**Issue by Alttaf** [Textalk/angular-schema-form#398]
Hi Guys,

When trying to style a manually inserted field using a standard bootstrap column definition,  The styling applied causes the field to become disabled.  For example:
```
 <div class="container">
   <div class="row">
     <form name="pers" sf-schema="personal" sf-form="personal_form" sf-model="modelPers"  ng-submit="onSubmit(pers,0,1)">
    <div class ="col-md-6">
     <div sf-insert-field="['firstname']"></div>
     </form>
   </div>
 </div>
```
Results in the form being styled, but the field becoming unavailable for selection like it is disabled.  Another thing to note that this is taking place in a angular-ui accordian, although I am pretty sure that shouldn't matter.

**Comment by davidlgj** [comment]
Sounds like another element with a transparent background is covering it, try inspecting in developer tools and see what you actually hit when clicking, you can also check if the input is disabled, but if it was then it probably would look disabled as well.

**Comment by Alttaf** [comment]
Hi David,

Thanks for your tip,  I looked in the inspector previously but didn't see anything that leapt out at me,  after considering the fact that something could be hiding I found the "boostrap decorator" covering my input.  

This only occurred when I mixed manual field insertion with the default schemaForm insertion for example 
'''
form = [
"firstname",
"lastname"
  {
    "type": "submit",
    "style": "btn-info",
    "title": "Submit"
  }
]

            <div class ="col-md-6">
            <div sf-insert-field="['firstname']"></div>          
            </div>
          
'''
The other fields where rendered afterwards and caused the bootstrap decorator to overlay the first name field,  the submit button also did not behave as expected

I rectified this by adding a key to the submit button and inserting all fields manually:
'''

form = [
"firstname",
"lastname"
  {
    "key" : "sub",
    "type": "submit",
    "style": "btn-info",
    "title": "Submit"
  }
]

            <div class ="col-md-6">
            <div sf-insert-field="['firstname']"></div>      
            <div sf-insert-field="['lastname']"></div> 
            </div>
            <div class ="col-md-6">
            <div sf-insert-field="['sub']"></div>
            </div>
'''

hope this helps someone else
