### ISSUE TITLE
Tabarray starting index.

### ISSUE THREAD

**Issue by chiewmey** [Textalk/angular-schema-form#402]
Hi, may I get your advice how can we set the starting index in tabarray from 1 instead of 0?

**Comment by Dervisevic** [comment]
Why do you need this? Is it for display reasons? Then you could just take the index and always +1.

**Comment by chiewmey** [comment]
Sorry, just get it resolved by adding bracket. 
"title":"'list '+($index+1) || 'list '+$index",
