### ISSUE TITLE
How do I define the form Schema json to hide a field

### ISSUE THREAD

**Issue by techrich** [Textalk/angular-schema-form#408]
How do I define the form Schema json to set the show and hide of the control rendered on the View?
 In other words: What standard/non-standard option is used to set a field to be hidden on the html that represents the "ng-show" property of AngularJS?

**Comment by Knuckles9090** [comment]
Correct me if I misunderstood your question. I think you would be looking for the "condition" option. If the condition rule is true, the field is shown.

**Comment by Dervisevic** [comment]
Yeah what @Knuckles9090 said. Full documentation here: https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#condition

**Comment by ashish2309** [comment]
So, is there way to hide and show a field on the basis of value (not boolean) in some other field, a condition like
{
		"key" : "parentId",
		"type": "number",
                "condition" : "scope.childType=='XYZ'"
}
