### ISSUE TITLE
is there a way to use ["*"] as a form but overwrite some form definitions?

### ISSUE THREAD

**Issue by ricklxm** [Textalk/angular-schema-form#409]
This is not a bug but a question. Sorry if I post it in wrong place.

Scenario:
I have many forms view to implement. And most of them have really huge schema definitions, I don't want to repeat it in form. So I wonder if there is a way to use ["*"] to inherit most definitions from schema, and then overwrite some fields as below???
                 "form":
                            [
                                "*",
                                {
                                    // overwrite field: refundEvents
                                    "key": "refundEvents",
                                    "add": null,
                                    "remove": null,
                                    "notitle": true,
                                    "items": [
                                        "refundEvents[].status",
                                        "refundEvents[].reason",
                                        "refundEvents[].employeeName",
                                        "refundEvents[].created"
                                    ]
                                }
                            ]

Thanks in advance!

**Comment by Dervisevic** [comment]
You can't do it like that, but if you can modify the schema you can use x-schema-form to set the form default for that specific field, see documentation here: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#form-defaults-in-schema

**Comment by ricklxm** [comment]
It works! Thanks very much!
