### ISSUE TITLE
change tabs event

### ISSUE THREAD

**Issue by punknroll** [Textalk/angular-schema-form#410]
Hi,

I need some action when I switch a tab. How can I do this? Thanx.

**Comment by davidlgj** [comment]
The tab is switched by the ng-click here: https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/tabs.html#L5

So you could replace this template and add some callback in the ng-click, another way/hack would be to get the scope and watch the `selected.tab` variable.

**Comment by punknroll** [comment]
Watching the selected.tab worked. Thank you.

**Comment by kaces** [comment]
May I ask how you would get the scope in order to access selected.tab variable?
Thank you

**Comment by jamiephillips0000** [comment]
I would also like to know how you watched the selected tab?

**Comment by sirius2013** [comment]
@punknroll 
could you provide example code about `Watching the selected.tab`? Thanks
