### ISSUE TITLE
Use HTML5 date input?

### ISSUE THREAD

**Issue by sharpmachine** [Textalk/angular-schema-form#412]
Hey there.  Is there a way to just use the HTML5 date input rather then using the datepicker addon?

Thanks!

**Comment by davidlgj** [comment]
Yes there is! There is a sort of a hack to support the html types. Any form definition "type" (not json schema type) that can't be matched with the `default.html` template, which is basically an `<input type="{{form.type}}">`. So in your form definition just use `"type": "date"`.

Here is an example:
http://schemaform.io/examples/bootstrap-example.html#/c2fee7e16a1e2cc9a2a6

**Comment by sharpmachine** [comment]
Oh wow.  That was easy.  Thanks so much.

**Comment by sharpmachine** [comment]
So just noticed that there's a validation error on the input:

![screen shot 2015-06-03 at 8 47 34 am](https://cloud.githubusercontent.com/assets/600836/7964588/5acbbdd6-09cd-11e5-9ead-b51e32e640f5.png)

**Comment by mike-marcacci** [comment]
Just want to chime in and say I noticed this the other day as well. It looks like angular parses `[type=date]` form fields into a javascript `Date` object as the `ng-model`. I don't immediately see a way to disable behavior, so we may need to use a formatter / parser to coerce it back into a string...

https://docs.angularjs.org/api/ng/input/input%5Bdate%5D

**Comment by sharpmachine** [comment]
I found the way around it was to also set type to 'date' in the schema, rather then string.

However I also noticed that for a title to be set it has be set in the form rather than schema...title in the schema doesn't work.

**Comment by mike-marcacci** [comment]
Hmm, `"date"` is not a valid json-schema type, and should probably be avoided...

**Comment by cristoferdomingues** [comment]
nobody resolve this problem?

**Comment by davidlgj** [comment]
Damn I didn't realize it got formatted to a `Date`. That sucks. Dates in JSON Schema's are of type string. So there needs to be a `$formatter` and a `$parsers` tacked on that translates between the string form and the, you can add them to the form definition https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#using-ngmodelcontroller
