### ISSUE TITLE
Angular schema form default not picking up

### ISSUE THREAD

**Issue by senthilsendhil** [Textalk/angular-schema-form#417]
we are using angular-schema-from for rendering form from json schema and json from

Some how we are not getting default value for enum,
```javascript
{
    "type": "object",
    "title": "Comment",
    "properties": {
        "contactDetails": {
            "title": "Contact Person",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "contactType": {
                        "title": "Contact Type",
                        "description": "Select",
                        "type": "string",
                        "default": "test",
                        "enum": ["test", "test1"]
                    }
                }
            }
        }
    }
}


[
    "contactDetails[].contactType",
    {
        "type": "submit",
        "style": "btn-info",
        "title": "OK"
    }
]

**Comment by nicklasb** [comment]
Hi,
Please edit your message and put the JSON in a code block so that the indent is visible.

**Comment by senthilsendhil** [comment]
@nicklasb its ok now?

**Comment by nicklasb** [comment]
Great! I am actually not being picky, remember that when you are asking for help, one should try and make the helper's job as easy as possible. Or you might not get any help.

**Comment by nicklasb** [comment]
Hi, so the reason is that you are editing an array, not a single entry.
So you need to define the form for the array as well:


    [
            {
                "key": "contactDetails",
                "title": "The array",
                "type" : "array",
                "items": [
                    "contactDetails[].contactType"
                 ]
            },
            {
                "type": "submit",
                "style": "btn-info",
                "title": "OK"
            }

    ]

In these cases, it is usable to try out the schema and model in the [demo-page](http://schemaform.io/examples/bootstrap-example.html)

By the way, to try it out in the demo, you need to add the schema first to the demo, or else the existing form will conflict with the new one.

**Comment by senthilsendhil** [comment]
@nicklasb Thanks for kind reply , I got some more issue, 

I just renamed ContactType to contact, its stopped working , any idea?

Please see below Form and Schema 

```javascript

{
    "type": "object",
    "title": "Comment",
    "properties": {
        "contactDetails": {
            "title": "Contact Person",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "contact": {
                        "title": "Contact Type",
                        "description": "Select",
                        "type": "string",
                        "default": "test",
                        "enum": ["test", "test1"]
                    }
                }
            }
        }
    }
}


[
        {
            "key": "contactDetails",
            "title": "The array",
            "type" : "array",
            "items": [
                { "key":"contactDetails[].contact"}
              
               
             ]
        },
        {
            "type": "submit",
            "style": "btn-info",
            "title": "OK"
        }

]

**Comment by nicklasb** [comment]
I saw a response from you that was removed, does this mean that this issue i resolved and can be closed?

**Comment by davidlgj** [comment]
:D @nicklasb I answered the SO post http://stackoverflow.com/questions/30639587/angular-schema-form-default-not-picking-up

I'm closing the issue since the solution you've written is the correct one.

**Comment by nicklasb** [comment]
Wow, thanks for stealing my SO rep points. :-)

**Comment by nicklasb** [comment]
BTW, how do you do that example-example that you refer to?

**Comment by davidlgj** [comment]
@nicklasb The "save to gist" button up in the top left corner! Then copy paste the "link" value.

**Comment by senthilsendhil** [comment]
@nicklasb  yes this issue solved, Thanks for help

**Comment by nicklasb** [comment]
Cool! I hadn't noticed that, and as it would appear, not many others.
I think the "Now you can save your code and share it!" isn't clear enough, it doesn't associate properly when you read:
"By pressing the 'Save to gist' button, you can save your example into a shareable gist-link."
