### ISSUE TITLE
empty required fields not taken in count for validation  

### ISSUE THREAD

**Issue by benoittoulme** [Textalk/angular-schema-form#421]
In the example: http://schemaform.io/examples/bootstrap-example.html

Although there are required fields, just after loading the page the form is said to be valid. But the required name field is empty, for example.

Not only the email field is in the 'required' fields list, but it also must validate the pattern "^\\S+@\\S+$", which a empty (or null) string does not validate. 

If I input something and delete it after in the email field, the email field is then empty and the form is not valid anymore. So the same empty form, valid at first, is now invalid, which is inconsistant.

Shouldn't these issues be taken in count in the validation? I think the user should not be able to submit an empty form or empty fields when they are set to be required.

**Comment by thardyman** [comment]
I agree.  I'm trying to upgrade from version 0.7.6 where this was working as expected to 0.8.2 and now it's not working.

**Comment by davidlgj** [comment]
It's recommended to issue a `schemaFormValidate` event before submission, see docs for example: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#handling-submit

**Comment by benoittoulme** [comment]
Thank you for your answer David.
The solution you provided is not solving 100% of my problem though I think I should be able to work it out.

For your information, here is what I am trying to do:
A wizard containing a different form at each step.
Forms with required fields, with fields with a validation pattern.
At each step of the wizard, a button that is displayed only when the form is valid, to enable the user to go to the next step.

In this case, I guess I could:
     - Watch the form's model, and use  schemaFormValidate to validate on change. I do not like the idea of broadcasting an event anytime a user modifies a field of the form, and I think you try to avoid watch functions as much as possible in the library.
      - Let the button appear in incorrect cases and validate on submit, which could be confusing for the user but would require less resources. I think I will go with this solution.

One feature which could be interesting for you in this case: a way to know when a form has been completed so the user can go to the next step (if the form is used in a wizard) or submit.

I use angular-schema-form with angular-wizard (https://github.com/mgonto/angular-wizard) and the result  is very nice. Your library reduced my code by x number of error-prone hard-to-read lines... 

Thank you and great job.
