### ISSUE TITLE
custom type in angular form schema

### ISSUE THREAD

**Issue by azadacme** [Textalk/angular-schema-form#437]
i am trying to create a new type "docSeries" i have created js file and made changes in bootstrap-decorators.js . bt still browser give me error:- Not Found - http://localhost:8081/acme-infinity-web/directives/decorators/bootstrap/docSeries/docSeries.html". because of this html is not rendered.

pls help me

**Comment by azadacme** [comment]
my schema:- {
    "type": "object",
    "title": "Comment",
	 "properties": {
	     "name": {
	       "title": "Name",
	       "type": "string"
	     },
	     		     
	     "address": {
	       "title": "Address",
	       "type": "string"
	     },
	     
	     "series":{
	       "title" : "Default Series",
	       "type"  : "string"
	     },
 					    
	     "pincode": {
	       "title": "Pincode",
	       "type": "string"
	     }
}

form with new type:- 
 {
          "Key" : "series",
          "type":"docSeries"
        }

**Comment by azadacme** [comment]
my js file:-

angular.module('schemaForm').directive('docSeries',function(){
	
	console.log('directive');
	
	var definitionObject = {
			restrict: 'A',  
			link : function(scope,element,attr){
				scope.docSeries = "RM";
				scope.docSeries.setting = {
						"readonly" : true,
						"charLimit" : 2
				};
			}			 
	};

	return definitionObject;
	
});

angular.module('schemaForm').config(
		['schemaFormProvider', 'schemaFormDecoratorsProvider', 'sfPathProvider',
		  function(schemaFormProvider,  schemaFormDecoratorsProvider, sfPathProvider) {

			var docSeries = function(name, schema, options) {
				   //console.log(name);
				  if (schema.type === 'string' && schema.title === 'Default Series') {
				    var f = schemaFormProvider.stdFormObj(name, schema, options);
				    f.key = options.path;
				    f.type = 'docSeries';
				    options.lookup[sfPathProvider.stringify(options.path)] = f;
				    //console.log(options.lookup[sfPathProvider.stringify(options.path)]);
				    return f;
				  }
				};

				// Put it first in the list of functions
				schemaFormProvider.defaults.string.unshift(docSeries);	
			
     
		    //Add to the bootstrap directive
			schemaFormDecoratorsProvider.addMapping(
					      'bootstrapDecorator',
					      'docSeries',
					      'directives/decorators/bootstrap/docSeries/docSeries.html'
					    );				
			schemaFormDecoratorsProvider.createDirective(
					      'docSeries',
					      'directives/decorators/bootstrap/docSeries/docSeries.html'
		    );
		
			    
		  }
]);

**Comment by azadacme** [comment]
my html:- 
<div class="form-group" ng-class="{'has-error': hasError()}">
  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>

  <input ng-show="form.key"
         style="background-color: white"
         type="text"
         class="form-control"
         schema-validate="form"
         ng-model="$$value$$"
         doc-series
          />
</div>

**Comment by azadacme** [comment]
HTML:- 

<div class="form-group" ng-class="{'has-error': hasError()}">
  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>

  <input ng-show="form.key"
         style="background-color: white"
         type="text"
         class="form-control"
         schema-validate="form"
         ng-model="$$value$$"
         doc-series
          />
</div>

**Comment by nicklasb** [comment]
You will probably have to add that file to the template cache. Most add-ons use a builer like gulp to generate that code.

**Comment by azadacme** [comment]
@nicklasb:- solve my problem... yes your right i hv to add dat file to template cache..
