### ISSUE TITLE
Updates to enum fields through model aren't reflected in UI

### ISSUE THREAD

**Issue by hola-senior** [Textalk/angular-schema-form#465]
Setting a value for an enum field through the model doesn't correctly update the selected enum's option in the UI; instead the 'blank' option is selected: http://jsfiddle.net/txmq7qr8/2/. 

This occurs even when using angular 1.4, unlike #458.

**Comment by davidlgj** [comment]
In release 0.8.4 I reverted a PR regarding selects that seems to caused a couple of bugs. Since the fiddle is against the development branch it now seems like it works :)
