### ISSUE TITLE
TitleMap Example does not work

### ISSUE THREAD

**Issue by Ventzy** [Textalk/angular-schema-form#471]
Here http://schemaform.io/examples/bootstrap-example.html when "TitleMap Examples" is selected on the left I see that first select is empty - it does not show "a", although in the "Model" section I see this
{
  "select": "a"
}

I beleive, when the model says its value is "a", then the select must show "a".

And maybe the real problem is that select/enum value is not rendered when model object has default value nor when model object value is changes after form is rendered. If the field is text its OK in both cases. Here is plunker http://plnkr.co/edit/NtqqyKgtVcM0oKTLpfYW?p=preview I except
1. When form is rendered for the first time "Type" field to show "type1"
2. When I click "Do set object value" button value of "Type" field to be changed to "type2"

**Comment by nicklasb** [comment]
I agree, this is strange, there is an existing issue for this issue though, enum is not initiated when the type in the form is explicitly set:
https://github.com/Textalk/angular-schema-form/issues/462

**Comment by davidlgj** [comment]
This was due to PR https://github.com/Textalk/angular-schema-form/pull/418 which I just reverted in release 0.8.4.
