### ISSUE TITLE
select doesn't show its initial value

### ISSUE THREAD

**Issue by aromanovich** [Textalk/angular-schema-form#473]
Here is a plunker to reproduce the bug: http://plnkr.co/edit/hGJJAZpd67uVpJlJBYlt?p=preview

It seems to be introduced in 0.8.3 with the [b7fb23a](https://github.com/Textalk/angular-schema-form/pull/418/files#diff-b7fb23ab1fda485328f4ece15a745a38R12) commit.
Angular docs says `as` and `track by` must not be used together: https://docs.angularjs.org/api/ng/directive/ngOptions#-select-as-

**Comment by nicklasb** [comment]
I agree, this is strange, there is an existing issue for this issue, enum is not initiated when the type in the form is explicitly set:
#462

**Comment by AlexAlbala** [comment]
Yes, the error appeared to me last week, just when they introduced the "trackBy" element

**Comment by nicklasb** [comment]
Sorry, removed the link above, this is a somewhat different bug, even though the symptoms are similar.

**Comment by AlexAlbala** [comment]
@aromanovich is right, I just removed the "track by item[form.trackBy]" element from the template of the select and voilà, worked lilke a charm!

**Comment by davidlgj** [comment]
This was due to https://github.com/Textalk/angular-schema-form/pull/418 which is reverted in release 0.8.4.
