### ISSUE TITLE
Is there a way to access the model in a custom controller

### ISSUE THREAD

**Issue by ngabello** [Textalk/angular-schema-form#504]
I have created a custom control to retrieve address based on zipcode, I have the html which has the postal input, when the user enters the zipcode the controller calls an api to get the address. What I really want to do is add the address to the model, is there a simple way to do this or do I have to use a service or use $parent.$parent.$parent.model. 
/************************************************************************************************************************/
schema: {
                        "type": "object",
                        "properties": {
                            "postalCode": {
                                type: 'string',
                                format: 'postalCodeSelector',
                                minLength: 5,
                                maxLength: 5
                            }
                        },
                        "required": [
                            "postalCode"
                        ]
                    },
                    form: [
                        {
                            key:"postalCode",
                            placeholder:"Zip Code",
                            notitle:true
                        }
                    ]
/********************************************************View*******************************************************/
<div class="input-group" ng-controller="PostalCodeSelectorController">
  <ng-form name="autoZipForm">
    <div id="step-postal-code">
      <div id="postal-code" class="">
        <div class="input-group">
          <div class="form-group"
               ng-class="{true: 'has-error'}[postalSummary.formSubmitted && autoZipForm.customerZip.$invalid]">

            <div ng-messages="autoZipForm.customerZip.$error" ng-if="postalSummary.formSubmitted">
              <div ng-message="required">Please enter a postal code.</div>
              <div ng-message="pattern">Please enter a valid postal code.</div>
              <div ng-message="invalidCode">Please verify your postal code.</div>
            </div>
            <input id="customerZip" name="customerZip" class="form-control {{form.fieldHtmlClass}}"
                   type="tel"
                   ng-pattern="/\d{5}/"
                   maxlength="5"
                   placeholder="{{form.placeholder}}"
                   ng-disabled="form.readonly"
                   ng-model-options="form.ngModelOptions"
                   ng-model="$$value$$"
                   required>
          </div>
          <div class="button-continue">
            <button class="" style="font-size:20px;" id="btnStartMe"
                    ng-click="getZipCode(autoZipForm.$valid, $$value$$)">
              <span>Start Me</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </ng-form>
</div>

/*****************************************************************************************************************/
angular.module('schemaForm').config(
    ['schemaFormProvider', 'schemaFormDecoratorsProvider', 'sfPathProvider',
        function (schemaFormProvider, schemaFormDecoratorsProvider, sfPathProvider) {

            var postalCodeSelector = function (name, schema, options) {
                if ((schema.type === 'string') && schema.format == 'postalCodeSelector') {
                    var f = schemaFormProvider.stdFormObj(name, schema, options);
                    f.key = options.path;
                    f.type = 'postalCodePicker';
                    options.lookup[sfPathProvider.stringify(options.path)] = f;
                    return f;
                }
            };

            schemaFormProvider.defaults.string.unshift(postalCodeSelector);

            //Add to the bootstrap directive
            schemaFormDecoratorsProvider.addMapping(
                'bootstrapDecorator',
                'postalCodePicker',
                'app/directives/decorators/postalCodeSelection/postalCodeSelector.html'
            );
            schemaFormDecoratorsProvider.createDirective(
                'postalCodePicker',
                'app/directives/decorators/postalCodeSelection/postalCodeSelector.html'
            );
        }]);

angular.module('schemaForm')
    .controller('PostalCodeSelectorController', ['$scope', 'geoCodeDataService', function ($scope, geoCodeDataService) {

        $scope.postalSummary = {
            formSubmitted:false,
            zipCode:null,
        };

        $scope.getZipCode = function ($valid, modelValue) {

            $scope.postalSummary.formSubmitted = true;
            $scope.autoZipForm.customerZip.$setValidity('invalidCode', true);
            //modelValue = $scope.autoZipForm.customerZip.$modelValue.toString();
            if ($valid) {

                geoCodeDataService.getPostalCodes($scope.autoZipForm.customerZip.$modelValue.toString()).then(function (results) {

                    if (results.data.HasRatedLocations && results.data.RatedLocations && results.data.RatedLocations.length > 0) {
                        $scope.autoZipForm.customerZip.$setValidity('invalidCode', true);

                        //Save the counties by selecting unique TerritoryCodes
                        var locations = _.uniq(results.data.RatedLocations, function (location) {
                            return location.County;
                        });

                        var address = {
                            City: locations[0].City,
                            State: locations[0].StateAbbreviation,
                            PostalCode: locations[0].PostalCode,
                            AddressType: 'Physical',
                            Counties: []
                        };

                        if (locations.length > 1) {
                            _.each(locations, function (location) {
                                address.Counties.push({
                                    Name: location.County,
                                    StateAbbreviation: location.StateAbbreviation
                                })
                            });
                        } else {
                            address.Counties.push({
                                Name: locations[0].County,
                                StateAbbreviation: locations[0].StateAbbreviation
                            })
                        }

                        modelValue = address;

                    } else if (!results.data.HasRatedLocations) {
                        $scope.autoZipForm.customerZip.$setValidity('invalidCode', false);
                    } else {
                        $scope.autoZipForm.customerZip.$setValidity('invalidCode', false);
                    }
                });
            }
        }
}]);

**Comment by ngabello** [comment]
Sorry here is the HTML
![capture](https://cloud.githubusercontent.com/assets/6154487/9228506/c6673fc0-40e6-11e5-8372-b2e4eac4d87a.PNG)

**Comment by nicklasb** [comment]
Well, $parent.$parent.$parent.model is a little bit brittle, doesn't take much of an ASF upgrade to break that, so I feel your pain. But currently, I don't think that there is any really beautiful solution to this one.

But this question will become more frequent, this is a common in desktop applications, and if I myself is an indication, more and more desktop developers will use ASF to migrate their desktop apps.

**Comment by ngabello** [comment]
I definitely agree with the $parent.$parent.$parent.model, so I went the service route with success. Thanks
