### ISSUE TITLE
Enhancement: Support Input Addons (optional icons for generic inputs : text)

### ISSUE THREAD

**Issue by warhawk3407** [Textalk/angular-schema-form#507]
Hello,

I was surprised that this great micro framework doesn't support bootstrap Input group addons, as described here : http://getbootstrap.com/css/#with-optional-icons

I would be very glad to see an option in the schema in order to add some glyphicon or texts to my inputs, in order to beautify them ! :-p

I think it should be integrated in bootstrap-decorator.

By the way, nice work guys, keep it up ! :+1: 

I will implement angular-schema-form in my own project @warhawk3407/bgpanelv2

Best regards

**Comment by TrevorPage** [comment]
Just to check, the existing options `fieldAddonLeft` / `fieldAddonRight` don't achieve what you're referring to, do they...?

**Comment by warhawk3407** [comment]
Oups, you are absolutely right @TrevorPage !!

I'm able to do what I want with : fieldAddonLeft: '<span class=\"glyphicon glyphicon-user\"></span>',

Thanks a lot !

This issue can now be closed.

**Comment by TrevorPage** [comment]
That's excellent. Also, in case it is of any interest, I recently did a modification to the angular-schema-form-dynamic-select library to enable support for `fieldAddonLeft` / `fieldAddonRight` on select menus, too. (As standard, you're limited to using it with just text boxes, etc.) It's just a pull request at the moment (https://github.com/OptimalBPM/angular-schema-form-dynamic-select/pull/34) but the same can also be achieved by registering a custom template.
