### ISSUE TITLE
Document the options parameter of $animate functions

### ISSUE THREAD

**Issue by djdmbrwsk** [Textalk/angular-schema-form#510]
Unless I missed it, there is no documentation explaining the `options` parameter that is optional in a bunch of the `$animate` service's functions. Ex:

```js
$animate.enter(element, parent, [after], [options]);
```

I just spent a bit digging through the source to finally find you can pass in an object like this:

```js
{
  addClass: 'some-new-class',
  removeClass: ' some-old-class'
}
```

**Comment by davidlgj** [comment]
Hey @djdmbrwsk are you sure you made this issue on the right project?

**Comment by djdmbrwsk** [comment]
Face palm...sorry about that!
