### ISSUE TITLE
Schema.type in custom field always returns string

### ISSUE THREAD

**Issue by RhysJevons** [Textalk/angular-schema-form#511]
I'm trying to build a custom integer input field however the schema.type property that's used as an indentifier for what field to use is always of type string.

```javascript
angular.module('schemaForm').config(['schemaFormProvider',
    'schemaFormDecoratorsProvider', 'sfPathProvider',
    function(schemaFormProvider, schemaFormDecoratorsProvider, sfPathProvider) {
        // Set up property combination that will trigger this directive
        var stringInput = function (name, schema, options) {
          console.log("SCHEMA: "+JSON.stringify(schema));
          console.log("NAME : "+name);
          console.log("OPTIONS : "+JSON.stringify(options));

            if (schema.type === 'string') {
                var f = schemaFormProvider.stdFormObj(name, schema, options);
                f.key = options.path;
                options.lookup[sfPathProvider.stringify(options.path)] = f;
                return f;
            }
        };
        // Add our default to the defaults array
        schemaFormProvider.defaults.string.unshift(stringInput);

        // Second, we want it to show if someone has explicitly set the form type
        schemaFormDecoratorsProvider.addMapping('bootstrapDecorator', 'stringInput',
            'app/modules/json_schema_form/schema_form_string_input/schema_form_string_input.html');
    }]);
```

In the above code outputting schema.type will only show string type fields. How would i do something similar for an integer type?

**Comment by davidlgj** [comment]
Hi @RhysJevons,

the functions that determine what form definition a schema should have by default is split up by type, see https://github.com/Textalk/angular-schema-form/blob/development/src/services/schema-form.js#L233

So change `schemaFormProvider.defaults.string.unshift(stringInput);` to `schemaFormProvider.defaults.integer.unshift(stringInput);` or `schemaFormProvider.defaults.number.unshift(stringInput);` depending on what type you need.

**Comment by RhysJevons** [comment]
Perfect seems obvious now it's been pointed out! Thank you
