### ISSUE TITLE
Question regarding TabArray validation

### ISSUE THREAD

**Issue by ngabello** [Textalk/angular-schema-form#542]
I would like to validate the current tab in the tab array before the user can add another tab, is there a way to do this? I see the onChange which creates a watch so removing the last tab item will not work properly cause it will fire the onChange again. Validating the entire tabarray with the form is not a good user experience if one of the tabs not expanded is invalid the user would not see the error.

**Comment by davidlgj** [comment]
No, it's not possible as they are today. You could make a copy of them and have that as a basis for an add-on (or possibly a PR, sounds like a nice to have feature).
