### ISSUE TITLE
I18n fields label

### ISSUE THREAD

**Issue by a58az** [Textalk/angular-schema-form#548]
Hello, I translate labels with js function, it works perfectly also everything good in sf-form (labels translated). But in html doesn't update anything and ``$scope.$apply`` doesn`t help.

My small code example, function ``foo`` return string:
```
            {
                "key": foo(),
                "type": "textarea",
                "placeholder": "Make a comment"
            }
```

**Comment by davidlgj** [comment]
Hi @a58az, I'm not following what you're trying to do here. Maybe it's the `title` property you want to change?

**Comment by a58az** [comment]
Oh, thank you. I made a silly mistake, everything works with `title` property
