### ISSUE TITLE
Validation for checkboxes does not work with the new builder

### ISSUE THREAD

**Issue by punknroll** [Textalk/angular-schema-form#556]
Hi,

required checkboxes don't validate at all using the new builder. There is no ngModel.$error on the checkboxes. I used my previous plunkr with the current tag 0.8.10.

http://plnkr.co/edit/qvsyjw?p=preview

**Comment by davidlgj** [comment]
Hi @punknroll,

I first had a moment of "wait, what? Didn't I just fix the checkboxes?"... then I read the issue again and checked out your plunkr :)

I've made a fix for the bug, also migrated the radios/radios-inline fixes for validation to the angular-schema-form-bootstrap decorator. It needed changes to both repos so make sure to update them.  
(ASF 0.8.11 and decorator 0.1.2)

Also you probably want to add a `"minItems": 1` validation to your array. "Required" doesn't fail on an empty array, it only fails on `undefined`. 

cheers

**Comment by punknroll** [comment]
Cool thanx!
