### ISSUE TITLE
Model field dependencies - a question

### ISSUE THREAD

**Issue by lafar6502** [Textalk/angular-schema-form#579]
Hi, i've got a question about expressing dependencies between form fields. I know that you can show or hide a field based on condition expression, but what about other scenarios like:
- hide or show entire form section 
- make field required, editable or read only depending on other field values
- limit the options available in a select according to other values entered
- validation dependent on a combination of several field values

thanks, maybe there are some examples of the above?

PS your promotional video is really good!

**Comment by Anthropic** [comment]
1. hide or show entire form section is already supported using conditions
2 & 3. Add the field as many times as needed to the form definition with conditions to determine which is displayed
4. You can add your own validators, there are discussions about supporting anyOf and oneOf from json schema, I made my own directive to handle that validation.

**Comment by lafar6502** [comment]
thanks
