### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by virtualeconomycoin** [Textalk/angular-schema-form#587]
Hello,
First of all thanks for this great library.
in my project i have large xml files(over 50000 lines) and large xsd schemas(total 20000 lines nested).
I am converting xmls to jaxb classes and then to json.
I am also converting xsd s to json schemas.
I am trying to use angular schema form for the view part,so far so good, i got a few problems while trying to get it work because of my large and complex xsd structure but made some modifications(little ones) and get it working. 
After challenges i am stuck to a relatively smaller problem(at least it should be)
I want to use vertical "tabs" in my form definition. My tab items are not array so i cant use tab-array.And i cant modify my json schema to make it an array(json schema auto generated from xsd).
I cant find a way to make "tabs" vertical.
Can you help?
Thanks,
Emre

**Comment by virtualeconomycoin** [comment]
Please ignore, problem solved by updating bootstrap-decorator.min.js

**Comment by JHGitty** [comment]
@virtualeconomycoin You can close the issue.
