### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by tombisho** [Textalk/angular-schema-form#598]
I might not be using it correctly, but I don't think the demo website is working correctly.

**Comment by nicklasb** [comment]
In what way do you think it is not working correctly?

**Comment by tombisho** [comment]
When I raised the issue, it was not working at - it was not possible to
select the different forms etc from the drop down.

Now I have looked again a few months later and all seems to be working fine.

**Comment by nicklasb** [comment]
Ok, can you close?
