### ISSUE TITLE
Weird delay when clicking into another input (or anything)

### ISSUE THREAD

**Issue by johannesspohr** [Textalk/angular-schema-form#613]
I'm experiencing some weird kind of delay / lag when changing the content of a field and trying to click into another one quickly. At first i thought it would be due to the complexity of my application with ckeditor and everything, but it occurs even on the demo form on the website. So for example try clicking into the second input while typing letters into the first one. It's only possible after not typing anything for like 2 seconds (tested on chrome and firefox). Since the delay is so constant and the model updates way earlier than i can exit the input, it feels like some kind of debounce mechanism or so.

**Comment by nicklasb** [comment]
Are you still having this problem?

**Comment by johannesspohr** [comment]
It's strange, sometimes it's there but a restart usually solves it for the moment. So i guess it's related to the performance of my machine.
